import fs from 'fs';

const translations = {
  ko: {
    'nav.home': '홈',
    'nav.tuina': '추나 마사지',
    'nav.diseases': '질병',
    'nav.ai_qna': 'AI Q&A',
    'lang.select': '언어 선택',
    'app.title': '건강한 아이들 (Sagdyn Çagalar)',
    'app.subtitle': '아이들의 건강과 보살핌을 위한 신뢰할 수 있는 플랫폼',
    
    'home.hero.title': '아이의 건강이 우리의 최우선입니다',
    'home.hero.subtitle': '소아 의료 정보, 추나 마사지 가이드 및 AI 어시스턴트를 갖춘 포괄적인 건강 플랫폼.',
    'home.hero.cta': '더 알아보기',
    'home.features.title': '주요 기능',
    'home.feature.tuina.title': '추나 마사지',
    'home.feature.tuina.desc': '어린이의 면역력과 건강을 향상시키는 고대 중국의 추나 마사지 기술.',
    'home.feature.diseases.title': '소아 질병',
    'home.feature.diseases.desc': '모든 유형의 소아 질병, 증상 및 치료에 대한 신뢰할 수 있는 정보.',
    'home.feature.ai.title': 'AI 어시스턴트',
    'home.feature.ai.desc': '자녀의 건강에 대한 질문을 하고 AI로부터 즉각적인 답변을 받으세요.',
    
    'tuina.title': '추나 마사지 가이드',
    'tuina.intro.title': '추나 마사지란 무엇인가요?',
    'tuina.intro.desc': '추나는 어린이 신체의 특정 혈자리를 마사지하여 질병을 치료하고 면역력을 높이는 전통 중의학의 한 분야입니다.',
    'tuina.history.title': '역사와 기원',
    'tuina.history.desc': '추나 마사지는 2,000년 이상 전통 중의학(TCM)의 핵심 요소였습니다. 체내 "기"(생명 에너지)의 흐름을 조절하고 자연 치유력을 향상시키는 데 중점을 둡니다. 소아과에 특화된 형태는 명나라(1368–1644) 시대에 발전했습니다.',
    'tuina.science.title': '과학적 근거',
    'tuina.science.desc': '현대 과학 연구에 따르면 추나 마사지는 아이들의 통증을 줄여주고, 스트레스 호르몬을 낮추며, 면역 체계를 강화하는 데 도움을 줍니다. 임상 시험에 따르면 이 방법은 특히 기침과 천식 증상을 완화하는 데 효과적입니다.',
    'tuina.testimonial.title': '부모님 후기',
    'tuina.testimonial.1.text': '"추나 마사지를 배운 후, 제 아이의 수면 패턴이 완전히 좋아졌습니다. 밤에 깨지 않고 평화롭게 잘 자게 되었습니다."',
    'tuina.testimonial.1.author': '— 아이굴 S., 2살 아이의 어머니',
    'tuina.testimonial.2.text': '"우리는 장 영아 산통으로 많이 고생했습니다. 매일 복부 마사지를 시작하자마자 아기가 편안해졌고 우는 횟수가 크게 줄어들었습니다."',
    'tuina.testimonial.2.author': '— 메르단 K., 6개월 아기의 아버지',
    'tuina.areas.title': '장기와 그 효능',
    'tuina.areas.desc': '추나 마사지는 아이의 특정 장기에 작용하여 정상적인 기능 향상에 도움을 줍니다.',
    'tuina.organ.1.name': '위와 장',
    'tuina.organ.1.benefit': '소화를 개선하고 복통을 줄여주며 식욕을 증진시킵니다.',
    'tuina.organ.2.name': '폐와 호흡기',
    'tuina.organ.2.benefit': '감기와 기침을 완화하고 숨쉬기를 편안하게 해줍니다.',
    'tuina.organ.3.name': '신장과 신경계',
    'tuina.organ.3.benefit': '수면의 질을 높이고 자연 면역력을 회복시킵니다.',
    'tuina.steps.title': '단계별 마사지 기술',
    'tuina.step.1.title': '1. 소화를 위한 복부 마사지',
    'tuina.step.1.desc': '아이를 똑바로 눕히세요. 배꼽 주위를 시계 방향으로 둥글게 원형으로 살살 문지릅니다 (3-5분간). 소화를 돕고 복통을 줄여줍니다.',
    'tuina.step.2.title': '2. 폐를 위한 가슴과 등 마사지',
    'tuina.step.2.desc': '가슴 중앙에서 바깥쪽으로 손바닥을 이용해 문지릅니다. 그 후 등 쪽 날개뼈 사이를 위아래로 부드럽게 마사지합니다 (뼈를 누르지 않도록 주의).',
    'tuina.step.3.title': '3. 면역력을 위한 척추 마사지',
    'tuina.step.3.desc': '손끝으로 척추를 아래에서 위로 부드럽게 쓰다듬습니다. 엄지손가락으로 아이의 손바닥 중앙과 발바닥 중앙을 가볍게 누릅니다.',
    'tuina.benefits.title': '건강상의 이점',
    'tuina.benefit.1': '면역 체계를 자연스럽게 강화시킵니다.',
    'tuina.benefit.2': '소화를 돕고 깊은 수면을 유도합니다.',
    'tuina.benefit.3': '열, 기침, 감기 증상을 크게 완화시킵니다.',
    
    'diseases.title': '소아 질병 라이브러리',
    'diseases.fever': '발열 및 감염',
    'diseases.respiratory': '호흡기 질환',
    'diseases.skin': '피부 질환',
    'diseases.digestive': '소화기 질환',
    'diseases.allergies': '알레르기',
    'diseases.category_select': '카테고리 선택',
    'diseases.category_select_desc': '질병 및 치료법을 봅니다',
    'diseases.categories.title': '카테고리',
    'diseases.categories.desc': '일반적인 소아 질환, 증상 및 집에서의 케어 방법을 보려면 아래 카테고리를 선택하세요.',
    'diseases.info.soon': '정보가 곧 추가될 예정입니다',
    'diseases.label.symptoms': '증상',
    'diseases.label.treatment': '치료 / 집에서의 케어',
    'diseases.data.fever.1.name': '일반 감기',
    'diseases.data.fever.1.symptoms': '콧물, 미열, 기침',
    'diseases.data.fever.1.treatment': '충분한 수분 공급과 휴식을 취하세요. 코막힘에 식염수를 사용하십시오. 4세 이하 어린이의 경우 소아과 의사와 상담하지 않고 시판 기침약을 사용하는 것을 피하십시오.',
    'diseases.data.fever.2.name': '독감 (인플루엔자)',
    'diseases.data.fever.2.symptoms': '고열, 근육통, 피로',
    'diseases.data.fever.2.treatment': '소아과 의사가 승인한 아세트아미노펜과 같은 해열제를 투여합니다. 호흡 곤란이나 평소와 다르게 심한 무기력증이 있는 경우 즉시 치료를 받으십시오.',
    'diseases.data.digestive.1.name': '위장염',
    'diseases.data.digestive.1.symptoms': '구토, 설사, 복통',
    'diseases.data.digestive.1.treatment': '자주 적은 양의 경구 수액제(ORS)를 투여하는 데 우선순위를 두십시오. 자극적이지 않은 음식(BRAT 식단)을 점차적으로 도입하십시오. 유제품과 단 음료는 피하십시오.',
    'diseases.data.respiratory.1.name': '천식',
    'diseases.data.respiratory.1.symptoms': '천명음, 숨가쁨, 흉부 압박감',
    'diseases.data.respiratory.1.treatment': '처방된 천식 행동 계획을 엄격하게 따르십시오. 악화될 시 속효성 흡입기를 사용하십시오. 먼지 및 애완동물 비듬과 같은 환경 유발 요인을 최소화하십시오.',
    'diseases.data.respiratory.2.name': '기관지염',
    'diseases.data.respiratory.2.symptoms': '가래 있는 기침, 피로감, 미열',
    'diseases.data.respiratory.2.treatment': '가습기를 사용하고 점액을 묽게 하기 위해 충분히 수분을 섭취합니다. 기침이 2-3주 이상 지속되거나 악화되면 의사와 상담하십시오.',
    'diseases.data.skin.1.name': '습진',
    'diseases.data.skin.1.symptoms': '건조하고 가렵고 붉은 반점',
    'diseases.data.skin.1.treatment': '목욕 후 즉시 두꺼운 무향 보습제를 바르십시오. 조절되지 않을 때는 처방받은 국소 코르티코스테로이드를 사용하십시오.',
    'diseases.data.skin.2.name': '수두',
    'diseases.data.skin.2.symptoms': '가려운 수포, 발열, 피로',
    'diseases.data.skin.2.treatment': '가려움증 완화를 위해 칼라민 로션이나 오트밀 목욕을 하세요. 이차 세균 감염을 방지하기 위해 손톱을 짧게 자르세요. 아세트아미노펜을 투여하십시오 (아스피린은 절대 피하십시오).',
    'diseases.data.allergies.1.name': '계절성 알레르기',
    'diseases.data.allergies.1.symptoms': '재채기, 콧물, 눈 가려움',
    'diseases.data.allergies.1.treatment': '비진정성 2세대 항히스타민제를 투여합니다. HEPA 공기청정기를 사용하고 꽃가루가 많은 계절에는 창문을 닫아 두십시오.',
    
    'qa.title': 'AI 의료 어시스턴트',
    'qa.subtitle': '아이의 건강, 질병 또는 관리 방법에 대해 질문하세요.',
    'qa.placeholder': '여기에 질문을 입력하세요...',
    'qa.send': '전송',
    'qa.error.empty': '죄송합니다. 정보를 찾을 수 없습니다.',
    'qa.error.connect': 'AI 지원팀에 연결하는 중 오류가 발생했습니다. 나중에 다시 시도해 주세요.',
    'qa.disclaimer': '(저는 투르크멘어, 러시아어, 영어, 독일어 및 한국어를 구사할 수 있습니다)',
    'qa.thinking': '생각 중...',
    'tuina.header.subtitle': '추나는 균형을 회복하고 치료에 초점을 맞춘 고대 중국의 치료용 마사지 기법입니다.',
    'tuina.benefits.1': '혈액 순환을 개선하고 휴식을 촉진합니다.',
    'tuina.benefits.2': '근육 긴장과 관절통을 완화합니다.',
    'tuina.benefits.3': '스트레스와 불안을 유발하는 요소를 감소시킵니다.',
    'tuina.benefits.4': '아이들의 소화 및 호흡기 문제를 도와줍니다.',
    'tuina.benefits.5': '유연성과 움직임의 범위를 개선합니다.',
    'tuina.techniques.title': '일반적인 추나 기법',
    'tuina.tech.1.title': '반죽하기 (Kneading)',
    'tuina.tech.1.desc': '손가락을 이용해 원을 그리며 근육을 이완시키고 혈류를 개선합니다.',
    'tuina.tech.2.title': '구르기 (Rolling)',
    'tuina.tech.2.desc': '사지 또는 척추를 따라 부드럽게 구르는 동작을 통해 뻣뻣함과 긴장을 완화합니다.',
    'tuina.tech.3.title': '누르기 (Pressing)',
    'tuina.tech.3.desc': '주요 혈자리에 직접적인 압력을 가해 기의 흐름을 자극하고 통증을 완화합니다.',
    'tuina.steps.title2': '추나 마사지 수행 방법: 단계별 안내',
    'tuina.step2.1': '1단계: 어린이 또는 환자를 편안하게 등을 대고 눕힙니다.',
    'tuina.step2.2': '2단계: 어깨를 둥글게 반죽하듯 부드럽게 주무르면서 근육을 풀어줍니다.',
    'tuina.step2.3': '3단계: 등과 척추에 굴리는 동작을 사용하여 피로를 풀어줍니다.',
    'tuina.step2.4': '4단계: 경락을 따라 혈자리에 가벼운 압박을 가하여 균형을 회복시킵니다.',
    'tuina.step2.5': '5단계: 부드럽고 매끄러운 동작으로 마무리하여 몸과 마음을 진정시킵니다.',
    'tuina.whentouse.title': '추나 마사지는 언제 받아야 할까요',
    'tuina.whentouse.intro': '추나는 아이와 어른 모두의 다음 질환을 치료하는 데 효과적입니다:',
    'tuina.whentouse.1': '변비나 복부 팽만감과 같은 소화기 문제.',
    'tuina.whentouse.2': '천식 및 기침과 같은 호흡기 질환.',
    'tuina.whentouse.3': '근육통, 뻣뻣함 및 관절 문제.',
    'tuina.whentouse.4': '스트레스 완화, 이완 및 수면 질 개선.',
    'tuina.children.title': '어린이를 위한 추나',
    'tuina.children.desc': '어린이용 추나는 아이의 필요에 맞춘 부드러운 압력과 달래는 기법으로 변형하여 사용할 수 있습니다. 약물을 사용하지 않고 아이들의 불편함을 완화시키는 데에 특히 도움이 됩니다.',
    'tuina.video.title': '비디오 튜토리얼 보기',
    'tuina.faq.title': '자주 묻는 질문',
    'tuina.faq.1.q': '이것은 안전한가요?',
    'tuina.faq.1.a': '네, 훈련받은 전문가에 의해 안전하게 수행되며, 어린이들도 받을 수 있도록 매우 부드럽게 조정됩니다.',
    'tuina.faq.2.q': '마사지 시간은 얼마나 지속되나요?',
    'tuina.faq.2.a': '어린이의 일반적인 세션은 아이의 연령과 상태에 따라 15-30분 정도 걸립니다.',
    'tuina.faq.3.q': '부모가 기대할 수 있는 효과는 무엇인가요?',
    'tuina.faq.3.a': '자녀가 훨씬 편안하고 푹 쉰 것을 느낄 수 있습니다. 이것은 전통적인 소아의학과 병행하는 보완 치료법으로 작용합니다.',
    
    'tuina.body.title': '신체 부위 및 기법',
    'tuina.body.1.title': '1. 머리와 얼굴',
    'tuina.body.1.how': '수행 방법: 이마: 손가락으로 이마에 작고 둥근 원을 그리며 가볍게 문지릅니다. 관자놀이: 양쪽 관자놀이를 가볍게 원을 그리며 마사지합니다. 눈 주위: 긴장을 완화하기 위해 눈과 눈썹 주위를 가볍게 누릅니다.',
    'tuina.body.1.benefits': '효과: 두통을 완화하고 눈의 피로를 감소시키며 아이가 차분해질 수 있도록 돕습니다.',
    'tuina.body.1.when': '언제 수행하나요: 아이가 잠들기 전 긴장을 풀어줄 때, 화면을 본 후나 스트레스 받는 활동 후에 눈의 피로를 줄이고 싶을 때.',
    
    'tuina.body.2.title': '2. 목과 어깨',
    'tuina.body.2.how': '수행 방법: 목: 엄지손가락으로 목을 따라 위치한 근육을 부드럽게 누르고 마사지합니다. 어깨: 손바닥으로 어깨 근육 위를 부드럽게 원형으로 마사지합니다.',
    'tuina.body.2.benefits': '효과: 목과 어깨의 긴장을 풀어주고, 올바른 자세에 도움을 주며 스트레스를 해소시킵니다.',
    'tuina.body.2.when': '언제 수행하나요: 긴 시간 앉아 있거나 놀이를 한 후에. 아이가 긴장하거나 스트레스를 받을 때.',

    'tuina.body.3.title': '3. 팔과 손',
    'tuina.body.3.how': '수행 방법: 팔: 가벼운 손길로 팔뚝을 위아래로 문지릅니다. 손: 엄지손가락으로 원을 그리며 손바닥과 손가락을 부드럽게 마사지합니다.',
    'tuina.body.3.benefits': '효과: 혈액 순환을 개선하고, 유연성을 증진시키며 손의 긴장을 완화시킵니다.',
    'tuina.body.3.when': '언제 수행하나요: 글씨를 쓰거나 기기를 사용한 후. 운동 전후 유연성을 높이기 위해.',

    'tuina.body.4.title': '4. 등과 척추',
    'tuina.body.4.how': '수행 방법: 척추: 손가락이나 엄지로 목에서 위부터 아래로 척추를 따라 부드럽게 마사지합니다. 허리 아래쪽: 아래 등 쪽에 가벼운 압력을 주고 손바닥으로 원 모양을 그리면서 부드럽게 마사지해줍니다.',
    'tuina.body.4.benefits': '효과: 등 통증을 완화하고 자세를 교정해 주며 휴식을 촉진합니다.',
    'tuina.body.4.when': '언제 수행하나요: 달리기나 스포츠와 같은 활동을 한 후에. 등에 피로를 덜어주기 위해 체류 후 장시간 자리에 앉아 있은 후.',

    'tuina.body.5.title': '5. 다리와 발',
    'tuina.body.5.how': '수행 방법: 발: 엄지손가락을 사용하여 발바닥과 발가락을 부드럽게 원을 그리며 마사지합니다. 다리: 다리부터 허벅지까지 긴 스트로크로 마사지합니다. 종아리와 허벅지를 가볍게 눌러줍니다.',
    'tuina.body.5.benefits': '효과: 다리에 나는 쥐를 완화시키고 혈류를 개선하며 아이가 건강하게 자랄 수 있도록 돕습니다.',
    'tuina.body.5.when': '언제 수행하나요: 뛰거나 운동을 하는 피지컬 활동 전과 후. 잠을 설치지 않고 편안하게 자도록 자기 전.',

    'tuina.timing.title': '추나 마사지는 언제 수행되어야 합니까?',
    'tuina.timing.daily': '매일 시행할 수 있습니다: 긴장을 풀고 건강한 신체를 위해 매일 실시할 수 있습니다.',
    'tuina.timing.special': '특별할 때: 운동과 엑티비티 활동 이후. 아이가 긴장하고 스트레스 받아 근육통을 가질 때. 그리고 두통이나 배탈 및 소화 불량시 수면의 질을 개선하기 위해.',

    'tuina.keybenefits.title': '어린이를 위한 추나 마사지의 핵심적인 장점들',
    'tuina.keybenefits.health': '건강상의 이점: 혈액 순환을 개선시키고 면역 체계를 강화하여 전반적인 건강 증진을 도모합니다.',
    'tuina.keybenefits.relieves': '일반적인 문제를 완화: 근육통, 두통, 소화 불량 증상을 가라앉혀줍니다.',
    'tuina.keybenefits.sleep': '수면 개선: 마음의 안정을 주고 우리 아이가 질 좋은 수면을 할 수 있도록 유도해 줍니다.',

    'footer.text': '© 2026 건강한 아이들(Sagdyn Çagalar). 판권 소유. 면책 조항: 이 웹사이트는 정보 제공의 목적으로만 사용되며 전문가의 의학적 조언을 대체하지 않습니다.',
  }
};

let content = fs.readFileSync('src/context/LanguageContext.tsx', 'utf-8');

// replace Language type
content = content.replace("export type Language = 'tk' | 'ru' | 'en' | 'de';", "export type Language = 'tk' | 'ru' | 'en' | 'de' | 'ko';");

// find const translations = { and add ko representation
const lastBracketIdx = content.lastIndexOf('};\n');

const koString = JSON.stringify(translations.ko, null, 4).replace(/"/g, "'").replace(/'([^']+)':/g, "'$1':");

const newContent = content.substring(0, lastBracketIdx) + ',\n  ko: ' + koString + '\n};\n' + content.substring(lastBracketIdx + 3);

fs.writeFileSync('src/context/LanguageContext.tsx', newContent);
