import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'tk' | 'ru' | 'en' | 'de' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isLanguageSelected: boolean;
  setIsLanguageSelected: (selected: boolean) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  tk: {
    'nav.home': 'Esasy sahypa',
    'nav.tuina': 'Tuina Massažy',
    'nav.diseases': 'Keseller',
    'nav.ai_qna': 'AI Sorag-Jogap',
    'lang.select': 'Dil saýlaň / Select Language',
    'app.title': 'Sagdyn Çagalar',
    'app.subtitle': 'Çaga saglygy we idegi üçin ynamdar platforma',
    
    // Home
    'home.hero.title': 'Çagalaryň saglygy iň uly baýlygymyz',
    'home.hero.subtitle': 'Pediatriýa lukmançylyk maglumatlary, Tuina massažy gollanmasy we emeli aň kömekçisi bilen çagalar üçin doly saglyk platformasy.',
    'home.hero.cta': 'Agza boluň / Öwreniň',
    'home.features.title': 'Biziň Hyzmatlarymyz',
    'home.feature.tuina.title': 'Tuina Massažy',
    'home.feature.tuina.desc': 'Çagalaryň immunitetini we saglygyny gowulandyrmak üçin gadymy hytaý Tuina massažy.',
    'home.feature.diseases.title': 'Çaga Keselleri',
    'home.feature.diseases.desc': 'Hemme görnüşli çaga keselleri, olaryň alamatlary we bejergisi barada ygtybarly maglumatlar.',
    'home.feature.ai.title': 'AI Sorag-Jogap',
    'home.feature.ai.desc': 'Çagaňyzyň saglygy barada islän soragyňyzy beriň we emeli aňdan derrew jogap alyň.',
    
    // Tuina
    'tuina.title': 'Tuina Massažy',
    'tuina.intro.title': 'Tuina massažy näme?',
    'tuina.intro.desc': 'Tuina massažy gadymy Hytaý lukmançylygynyň esasy böleklerinden biri bolup, çaganyň endamyndaky belli nokadelere edip, keselleri bejermek we immuniteti ýokarlandyrmak üçin ulanylýar.',
    'tuina.history.title': 'Taryhy we Gözbaşy',
    'tuina.history.desc': 'Tuina massažy 2000 ýyldan gowrak wagt bäri Hytaýyň adaty lukmançylygynyň (TCM) esasy bölegi bolup gelýär. Ol bedeniň "Qi" (ýaşaýyş energiýasy) akymyny sazlamaga we tebigy bejeriş ukybyny güýçlendirmäge gönükdirilendir. Çagalar üçin ýöriteleşdirilen görnüşi Min neberesi döwründe (1368–1644) kämilleşdirilipdir.',
    'tuina.science.title': 'Ylmy Taýdan Tassyklnan',
    'tuina.science.desc': 'Döwrebap ylmy barlaglar Tuina massažynyň çagalarda agyrylary azaldýandygyny, stres gormonlaryny peseldip, immunitetiň güýçlenmegine ýardam berýändigini subut etdi. Kliniki synaglar bu usulyň aýratynam üsgülewük we astma alamatlaryny egsedýändigini görkezýär.',
    'tuina.testimonial.title': 'Ene-atalaryň Tejribesi',
    'tuina.testimonial.1.text': '"Tuina massažyny öwrenenimden soň çagamyň uky tertibi doly gowulaşdy. Gijelerine oýanman rahat uklaýar."',
    'tuina.testimonial.1.author': '— Aýgül S., 2 ýaşly oglanjygyň enesi',
    'tuina.testimonial.2.text': '"Içege sancyjyklaryndan (kolik) köp kösenýärdik. Garyn massažyny gündelik edip başlanymyzdan soň, çagam rahatlandy we aglamasy onçakly azaldy."',
    'tuina.testimonial.2.author': '— Merdan K., 6 aýlyk gyzjagazyň kakasy',
    'tuina.areas.title': 'Agzalar we Olaryň Peýdasy',
    'tuina.areas.desc': 'Tuina massažy çaganyň belli agzalaryna täsir etmek bilen olaryň kadaly işlemegine ýardam berýär.',
    'tuina.organ.1.name': 'Aşgazan we Içege',
    'tuina.organ.1.benefit': 'Iýmit siňdirişi gowulandyrýar, içege sanjylaryny aýyrýar, işdäni açýar.',
    'tuina.organ.2.name': 'Öýken we Dem alys',
    'tuina.organ.2.benefit': 'Sowuklamany, üsgülewügi bejerýär, dem alşy ýeňilleşdirýär.',
    'tuina.organ.3.name': 'Böwrek we Nerw ulgamy',
    'tuina.organ.3.benefit': 'Uky hilini gowulandyrýar, bedeniň tebigy immunitetini dikeldýär.',
    'tuina.steps.title': 'Ädim-ädim massaž tilsimi',
    'tuina.step.1.title': '1. Aşgazan-içege garyn massažy',
    'tuina.step.1.desc': 'Çagany arkan ýatyryň. Garyn boşlugynda, göbegiň daşyndan sagat diliniň ugrunda ýuwaşja aýlawly hereketler bilen sypalaň (3-5 minut). Bu iýmit siňdirişi ýeňilleşdirýär we agyrylary aýyrýar.',
    'tuina.step.2.title': '2. Öýken üçin döş we arka sypalamasy',
    'tuina.step.2.desc': 'Aýaňyz bilen döş kapasasynda merkezden daşaryk sypalaň. Soňra arkasynda pilçe süňkleriniň arasynda aşak-ýokary ýuwaşja owkalaň (süňkün üstünden basmaň).',
    'tuina.step.3.title': '3. Nerw we Immunitet üçin oňurga owkalamasy',
    'tuina.step.3.desc': 'Barmak uçlaryňyz bilen oňurganyň gyrasyndan aşakdan ýokaryk sypalaň. Başama barmagyňyz bilen çaganyň aýasynyň ortasyna we dabanlaryna ýeňil basyş ediň.',
    'tuina.benefits.title': 'Peýdalary',
    'tuina.benefit.1': 'Immuniteti tebigy usul bilen ýokarlandyrýar.',
    'tuina.benefit.2': 'Iýmit siňdirişi we uky hilini gowulandyrýar.',
    'tuina.benefit.3': 'Gyzdyrma, üsgülewük we sowuklama alamatlaryny egsedýär.',
    
    // Diseases
    'diseases.title': 'Çaga Keselleri Kitapçasy',
    'diseases.fever': 'Gyzdyrma we ýokanç keseller',
    'diseases.respiratory': 'Dem alyş keselleri',
    'diseases.skin': 'Deri keselleri',
    'diseases.digestive': 'Iýmit siňdiriş kynçylyklary',
    'diseases.allergies': 'Allergiýa',
    'diseases.category_select': 'Kategoriýa saýlaň',
    'diseases.category_select_desc': 'keselleri we bejergileri görmek üçin',
    'diseases.categories.title': 'Kategoriýalar',
    'diseases.categories.desc': 'Aşakdaky kategoriýalardan birini saýlaň we çagalarda köp duş gelýän keseller, olaryň alamatlary we öý şertlerindäki bejergiler bilen tanyşyň.',
    'diseases.info.soon': 'Maglumat tiz wagtda goşular',
    'diseases.label.symptoms': 'Alamatlar',
    'diseases.label.treatment': 'Bejergi / Öý Şertleri',
    'diseases.data.fever.1.name': 'Adaty Sowuklama',
    'diseases.data.fever.1.symptoms': 'Burnuň akmagy, pes gyzdyrma, üsgülewük',
    'diseases.data.fever.1.treatment': 'Ýeterlik suwuklyk we dynç alyşy üpjün ediň. Burny arassalamak üçin duzly damjalary ýa-da spreýi ulanyň. 4 ýaşdan kiçi çagalary lukmansyz üsgülewük dermanlaryndan goraň.',
    'diseases.data.fever.2.name': 'Dümew (Flu)',
    'diseases.data.fever.2.symptoms': 'Ýokary gyzdyrma, bedeniň agyrmagy, ysmazlyk',
    'diseases.data.fever.2.treatment': 'Lukmanyň tassyklan dermanlaryny (ibuprofen/parasetamol) beriň. Dem alyş erbetleşse ýa-da gaty ysgynsyzlyk ýüze çyksa haýal etmän lukmana ýüz tutuň.',
    'diseases.data.digestive.1.name': 'Gastroenterit',
    'diseases.data.digestive.1.symptoms': 'Ýürek bulanma, içegänagyryjy, iç geçme',
    'diseases.data.digestive.1.treatment': 'Weýrançylygyň öňüni almak üçin ýygy-ýygydan ORS erginlerini beriň. Ýuwaş-ýuwaşdan ýeňil iýmitleri (banan, tüwi) giriziň. Süýt we süýji içgilerden saklanyň.',
    'diseases.data.respiratory.1.name': 'Dem alyş ýollarynyň sowuklamasy (Astma)',
    'diseases.data.respiratory.1.symptoms': 'Bökdençli dem alyş, döş gysylma, hiňňildik',
    'diseases.data.respiratory.1.treatment': 'Kesgitlenen astma bejergi meýilnamasyna berk eýeriň. Gysga wagtlaýyn dem alyş giňeldijilerini ulanyň. Ekologiýa triggerlerini aýyryň.',
    'diseases.data.respiratory.2.name': 'Bronhit',
    'diseases.data.respiratory.2.symptoms': 'Gakykly üsgülewük, ysgynsyzlyk, pes gyzdyrma',
    'diseases.data.respiratory.2.treatment': 'Salkyn bugarýan çyglandyryjy we gakygyň ýumşamagy üçin köp suwuklyk beriň. Üsgülewük 2-3 hepdeden köp dowam etse lukmana gidäň.',
    'diseases.data.skin.1.name': 'Ekzema',
    'diseases.data.skin.1.symptoms': 'Gury, gijilewükli, gyzyl tegmiller',
    'diseases.data.skin.1.treatment': 'Gysga ylyjak wannadan soň nemlendirijileri çalyň. Çylşyrymly ýagdaýlarda lukmanyň belän steroid melhemlerini ulanyň.',
    'diseases.data.skin.2.name': 'Suwçäçek',
    'diseases.data.skin.2.symptoms': 'Gijilewükli örgün we düwürtikler, gyzdyrma',
    'diseases.data.skin.2.treatment': 'Gijewügi aýyrmak üçin kalamin ýa-da süläli wannalary ulanyň. Dyrnaklaryny gysga tutuň. Gyzdyrma üçin parasetamol beriň (aspirini ulanmaň).',
    'diseases.data.allergies.1.name': 'Möwsümleýin Allergiýa',
    'diseases.data.allergies.1.symptoms': 'Hapgyrma, burun akma, göz gijilewük',
    'diseases.data.allergies.1.treatment': 'Uky getirmeýän antihistamin dermanlaryny we HEPA howa arassalaýjylary ulanyň. Möwsüminde penjireleri ýapyk saklaň.',
    
    // QA
    'qa.title': 'Emeli Aň Lukmançylyk Kömekçisi',
    'qa.subtitle': 'Çaga saglygy we keselleri barada islän maglumatyňyzy sorap bilersiňiz.',
    'qa.placeholder': 'Soragyňyzy şu ýere ýazyň...',
    'qa.send': 'Ugrat',
    'qa.error.empty': 'Kechirerin, maglumat tapyp bilmedim.',
    'qa.error.connect': 'Enjama baglanylyp bilinmedi. Soňurak gaýtadan synanyşyň.',
    'qa.disclaimer': '(Men Türkmen, Rus, Iňlis, Nemes we Koreý dillerinde gürleşip bilýärin)',
    'qa.thinking': 'Pikir edýär...',
    'tuina.header.subtitle': 'Tuina bedeniň deňagramlylygyny dikeltmäge gollanýan gadymy Hytaý bejeriş massaž usulydyr.',
    'tuina.benefits.1': 'Gan aýlanyşygy gowulandyrýar we rahatlandyrýar.',
    'tuina.benefits.2': 'Myşsa dartgynlygyny we bogun agyrylaryny ýeňilleşdirýar.',
    'tuina.benefits.3': 'Stresi we aladalary aýyrýar.',
    'tuina.benefits.4': 'Çagalaryň iýmit siňdiriş we dem alyş kynçylyklaryna peýdaly.',
    'tuina.benefits.5': 'Çeýeligi we hereket ukybyny artdyrýar.',
    'tuina.techniques.title': 'Esasy Tuina tilsimleri',
    'tuina.tech.1.title': 'Owkalamak (Kneading)',
    'tuina.tech.1.desc': 'Myşsalary rahatlamagy we gan aýlanyşygy gowulandyrmagy üçin barmaklar bilen aýlawly owkalamak.',
    'tuina.tech.2.title': 'Togalatmak (Rolling)',
    'tuina.tech.2.desc': 'Dartylyşlary aýyrmak üçin aýaklarda we oňurgada ýumşak togalamak (sypalamak).',
    'tuina.tech.3.title': 'Basyş (Pressing)',
    'tuina.tech.3.desc': 'Energiýa akymyny güýçlendirmek üçin esasy nokatlara gönüden-göni basyş etmek.',
    'tuina.steps.title2': 'Tuina Massažy Ädimme-ädim gollanmasy',
    'tuina.step2.1': '1-nji ädim: Çagany ýa-da syrkawy arkan ýatyryň.',
    'tuina.step2.2': '2-nji ädim: Egindäki myşsalary rahatlatmak üçin ýeňilçe owkalaň.',
    'tuina.step2.3': '3-nji ädim: Dartgynlygy aýyrmak üçin arkada we oňurgada togalama (sypalama) hereketlerini ediň.',
    'tuina.step2.4': '4-nji ädim: Deňagramlygy dikeltmek üçin möhüm nokatlara barmaklar bilen ýeňil basyş ediň.',
    'tuina.step2.5': '5-nji ädim: Bedeni we ünsi rahatlandyrmak üçin dowamly we ýumşak sypalaň.',
    'tuina.whentouse.title': 'Tuina massažyny haçan etmeli',
    'tuina.whentouse.intro': 'Tuina uly ýaşlylaryň we çagalaryň şu ýagdaýlarynda peýdalydyr:',
    'tuina.whentouse.1': 'Iç gatamasy we içege sowuklamalary ýaly iýmit siňdiriş kynçylyklarynda.',
    'tuina.whentouse.2': 'Astma we üsgülewük ýaly dem alyş kesellerinde.',
    'tuina.whentouse.3': 'Myşsa agyrylary we bogun kynçylyklarynda.',
    'tuina.whentouse.4': 'Stresden azat bolmak we ukyny gowulandyrmak üçin.',
    'tuina.children.title': 'Çagalar üçin Tuina',
    'tuina.children.desc': 'Tuina massažy gysga wagtda has ýumşak edilen halatynda dermansyz agyrylary ýeňilleşdirmäge gaty peýdalydyr.',
    'tuina.video.title': 'Wideo gollanma',
    'tuina.faq.title': 'Köp soralýan soraglar',
    'tuina.faq.1.q': 'Tuina howpsuzmy?',
    'tuina.faq.1.a': 'Hawa, ökde lukmanlar ýa-da öwrenen ene-atalar tarapyndan edilende Tuina çagalar üçin gaty howpsuz we zyýansyzdyr.',
    'tuina.faq.2.q': 'Massaž näçe wagt dowam edýär?',
    'tuina.faq.2.a': 'Çagalar üçin adatça 15-30 minut aralygynda bolýar.',
    'tuina.faq.3.q': 'Hili peýdasy bar?',
    'tuina.faq.3.a': 'Ene-atalar çagasynyň rahatlanmagyny, oňat uklaýandygyny görerler. Bu adaty derman bejergisi bilen ajaýyp utgaşýar.',
    'tuina.body.title': 'Beden Agzalary we Tilsimler',
    'tuina.body.1.title': '1. Kelle we Ýüz',
    'tuina.body.1.how': 'Nädip etmeli: Maňlaý: Barmaklaryňyz bilen maňlaýda kiçeňräk aýlawly hereketler bilen ýuwaşja owkalaň. Çekge: Iki çekgeden hem aýlawly owkalaň. Gözüň töweregi: Dartgynlygy aýyrmak üçin gözüň we gaşyň töweregine ýeňil basyş ediň.',
    'tuina.body.1.benefits': 'Peýdasy: Kelleagyryny aýyrýar, göz ýadamagyny azaldýar we çagany rahatlandyrýar.',
    'tuina.body.1.when': 'Haçan etmeli: Çaga ukamazdan öň rahatlanmak üçin. Ekrandan soň ýa-da stresli ýagdaýlardan soň gözüň ýadamagyny aýyrmak üçin.',
    'tuina.body.2.title': '2. Boýun we Eginler',
    'tuina.body.2.how': 'Nädip etmeli: Boýun: Başbarmaklaryňyz bilen boýun myşsalaryny ýeňil basyň we owkalaň. Eginler: Aýaňyz bilen egin myşsalarynda ýuwaşja aýlawly hereketler ediň.',
    'tuina.body.2.benefits': 'Peýdasy: Boýundaky we egindäki dartgynlygy aýyrýar, syratlylyga kömek edýär we stresi aýyrýar.',
    'tuina.body.2.when': 'Haçan etmeli: Köp wagt oturanyndan ýa-da oýnanyndan soň. Çaga dartgynly ýa-da stresli bolanda.',
    'tuina.body.3.title': '3. Gollar we Eller',
    'tuina.body.3.how': 'Nädip etmeli: Gollar: Barmaklaryňyz bilen gollarda ýokary-aşak sypalaň. Eller: Başbarmagyňyz bilen aýa we barmaklary aýlawly hereketler bilen owkalaň.',
    'tuina.body.3.benefits': 'Peýdasy: Gan aýlanyşyny gowulandyrýar, çeýeligi artdyrýar we ellerdäki dartgynlygy azaldýar.',
    'tuina.body.3.when': 'Haçan etmeli: Ýazandan ýa-da enjamlardan peýdalanandan soň. Çeýeligi artdyrmak üçin sportdan öň ýa-da soň.',
    'tuina.body.4.title': '4. Arka we Oňurga',
    'tuina.body.4.how': 'Nädip etmeli: Oňurga: Barmaklaryňyz bilen oňurga boýunça boýundan bil arkasyna çenli ýuwaşja owkalaň. Bil arkasy: Bil arkasyna ýeňilçe basyň we aýaňyzy aýlawly owkalaň.',
    'tuina.body.4.benefits': 'Peýdasy: Arka agyrylaryny aýyrýar, oňat syratlylyga kömek edýär we rahatlandyrýar.',
    'tuina.body.4.when': 'Haçan etmeli: Ylgaw ýa-da oýun ýaly bedenterbiýe işjeňliklerinden soň. Arka ýadamagyny azaltmak üçin köp oturylýan wagtlardan soň.',
    'tuina.body.5.title': '5. Aýaklar we Dabanlar',
    'tuina.body.5.how': 'Nädip etmeli: Daban: Başbarmaklaryňyz bilen kiçi aýlawlar edip dabany we barmaklary ýuwaşja owkalaň. Aýaklar: Aýaklardan butlara çenli uzyn sypalamalar ediň. Baldyra we butlara ýeňil basyň.',
    'tuina.body.5.benefits': 'Peýdasy: Aýak damar çekmesini azaldýar, gan aýlanyşygyny gowulandyrýar we sagdyn ösmegine ýardam berýär.',
    'tuina.body.5.when': 'Haçan etmeli: Ylgamak ýa-da sport oýnamak ýaly beden işjeňliklerinden öň ýa-da soň. Ukudan öň rahatlanmak üçin.',
    'tuina.timing.title': 'Tuina Massažy Haçan Edilmeli?',
    'tuina.timing.daily': 'Gündelik ulanmak: Rahatlygy saklamak we umumy saglygy ösdürmek üçin Tuinany gündelik edip bolýar.',
    'tuina.timing.special': 'Ýörite wagtlar: Sport ýa-da oýun ýaly beden işjeňliklerinden soň. Çaga stresli, dartgynly bolanda ýa-da myşsa agyrylary bolanda. Uky kynçylyklary, kelleagyry ýa-da iýmit siňdiriş kynçylyklarynda kömek etmek üçin.',
    'tuina.keybenefits.title': 'Çagalar üçin Tuina Massažynyň Esasy Peýdalary',
    'tuina.keybenefits.health': 'Saglyk peýdalary: Gan aýlanyşygyna kömek edýär, immunitet ulgamyny goldaýar we umumy saglygy gowulandyrýar.',
    'tuina.keybenefits.relieves': 'Adaty kynçylyklary aýyrýar: Myşsa dartgynlygyny, stresi, kelleagyrylary we iýmit siňdiriş kynçylyklaryny egisýär.',
    'tuina.keybenefits.sleep': 'Ukyny gowulandyrýar: Rahatlanmaga ýardam berýär we çagalaryň oňat uklamagyna kömek edýär.',

    'footer.text': '© 2026 Sagdyn Çagalar. Ähli hukuklar goralan. Üns beriň: Bu websaýt diňe maglumat bermek üçindir, lukmanyň maslahatyny çalyşmaýar.',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.tuina': 'Массаж Туйна',
    'nav.diseases': 'Болезни',
    'nav.ai_qna': 'ИИ Вопросы-Ответы',
    'lang.select': 'Выберите язык',
    'app.title': 'Здоровые Дети',
    'app.subtitle': 'Надежная платформа для здоровья и ухода за детьми',
    
    'home.hero.title': 'Здоровье вашего ребенка – наша забота',
    'home.hero.subtitle': 'Комплексная платформа с педиатрической информацией, руководством по массажу Туйна и ИИ-помощником.',
    'home.hero.cta': 'Узнать больше',
    'home.features.title': 'Наши разделы',
    'home.feature.tuina.title': 'Массаж Туйна',
    'home.feature.tuina.desc': 'Древний китайский массаж для улучшения иммунитета и здоровья детей.',
    'home.feature.diseases.title': 'Детские болезни',
    'home.feature.diseases.desc': 'Достоверная информация о детских заболеваниях, симптомах и лечении.',
    'home.feature.ai.title': 'ИИ-Помощник',
    'home.feature.ai.desc': 'Задайте любой вопрос о здоровье ребенка и мгновенно получите ответ от ИИ.',
    
    'tuina.title': 'Массаж Туйна',
    'tuina.intro.title': 'Что такое массаж Туйна?',
    'tuina.intro.desc': 'Туйна — это одна из ветвей традиционной китайской медицины, включающая массаж биологически активных точек ребенка для лечения и повышения иммунитета.',
    'tuina.history.title': 'История и происхождение',
    'tuina.history.desc': 'Массаж Туйна является основной частью традиционной китайской медицины (ТКМ) уже более 2000 лет. Он направлен на регулирование потока «Ци» (жизненной энергии) в организме и усиление способности к естественному исцелению. Специализированная форма для детей была усовершенствована во времена династии Мин (1368–1644 гг.).',
    'tuina.science.title': 'Научное подтверждение',
    'tuina.science.desc': 'Современные научные исследования доказывают, что массаж Туйна уменьшает боль у детей, снижает уровень гормонов стресса и помогает укрепить иммунитет. Клинические испытания показывают, что этот метод особенно облегчает симптомы кашля и астмы.',
    'tuina.testimonial.title': 'Опыт родителей',
    'tuina.testimonial.1.text': '"После того как я научилась массажу Туйна, режим сна моего ребенка полностью улучшился. Он спит спокойно, не просыпаясь по ночам."',
    'tuina.testimonial.1.author': '— Айгуль С., мама 2-летнего мальчика',
    'tuina.testimonial.2.text': '"Мы много страдали от кишечных колик. После того как мы начали делать массаж живота каждый день, мой ребенок расслабился, и плач значительно уменьшился."',
    'tuina.testimonial.2.author': '— Мердан К., папа 6-месячной девочки',
    'tuina.areas.title': 'Органы и их преимущества',
    'tuina.areas.desc': 'Массаж Туйна воздействует на নির্দিষ্ট органы ребенка, улучшая их нормальное функционирование.',
    'tuina.organ.1.name': 'Желудок и Кишечник',
    'tuina.organ.1.benefit': 'Улучшает пищеварение, снимает колики, повышает аппетит.',
    'tuina.organ.2.name': 'Легкие и Дыхание',
    'tuina.organ.2.benefit': 'Лечит простуду, кашель, облегчает дыхание.',
    'tuina.organ.3.name': 'Почки и Нервная система',
    'tuina.organ.3.benefit': 'Улучшает качество сна, восстанавливает естественный иммунитет.',
    'tuina.steps.title': 'Пошаговая техника массажа',
    'tuina.step.1.title': '1. Массаж живота для пищеварения',
    'tuina.step.1.desc': 'Положите ребенка на спину. Мягко поглаживайте живот круговыми движениями по часовой стрелке вокруг пупка (3-5 минут). Это облегчает пищеварение и снимает боль.',
    'tuina.step.2.title': '2. Массаж груди и спины для легких',
    'tuina.step.2.desc': 'Ладонью поглаживайте грудную клетку от центра наружу. Затем мягко массируйте спину между лопатками вверх и вниз (не давите на кости).',
    'tuina.step.3.title': '3. Массаж позвоночника для нервной системы',
    'tuina.step.3.desc': 'Кончиками пальцев поглаживайте вдоль позвоночника снизу вверх. Большим пальцем слегка надавливайте на центр ладоней и стоп ребенка.',
    'tuina.benefits.title': 'Преимущества',
    'tuina.benefit.1': 'Естественным образом повышает иммунитет.',
    'tuina.benefit.2': 'Улучшает пищеварение и качество сна.',
    'tuina.benefit.3': 'Облегчает симптомы лихорадки и простуды.',
    
    'diseases.title': 'Справочник детских болезней',
    'diseases.fever': 'Лихорадка и инфекции',
    'diseases.respiratory': 'Респираторные заболевания',
    'diseases.skin': 'Кожные заболевания',
    'diseases.digestive': 'Проблемы с пищеварением',
    'diseases.allergies': 'Аллергии',
    'diseases.category_select': 'Выберите категорию',
    'diseases.category_select_desc': 'чтобы просмотреть болезни и методы лечения',
    'diseases.categories.title': 'Категории',
    'diseases.categories.desc': 'Выберите категорию ниже, чтобы изучить распространенные детские заболевания, их симптомы и способы лечения в домашних условиях.',
    'diseases.info.soon': 'Информация скоро будет добавлена',
    'diseases.label.symptoms': 'Симптомы',
    'diseases.label.treatment': 'Лечение / Домашний уход',
    'diseases.data.fever.1.name': 'Простуда',
    'diseases.data.fever.1.symptoms': 'Насморк, небольшая температура, кашель',
    'diseases.data.fever.1.treatment': 'Обеспечьте отдых и адекватную гидратацию. Используйте солевые назальные спреи. Избегайте безрецептурных средств от кашля для детей до 4 лет.',
    'diseases.data.fever.2.name': 'Грипп',
    'diseases.data.fever.2.symptoms': 'Высокая температура, ломота в теле, усталость',
    'diseases.data.fever.2.treatment': 'Используйте одобренные педиатром жаропонижающие (ибупрофен/парацетамол). При одышке или сильной вялости немедленно обратитесь к врачу.',
    'diseases.data.digestive.1.name': 'Гастроэнтерит',
    'diseases.data.digestive.1.symptoms': 'Рвота, диарея, боль в животе',
    'diseases.data.digestive.1.treatment': 'Давайте растворы для пероральной регидратации (ОРС) небольшими порциями. Постепенно вводите щадящую диету (BRAT). Исключите сладкие напитки.',
    'diseases.data.respiratory.1.name': 'Астма',
    'diseases.data.respiratory.1.symptoms': 'Хрипы, одышка, стеснение в груди',
    'diseases.data.respiratory.1.treatment': 'Строго следуйте плану лечения. Используйте бронходилататоры при обострениях. Устраните пыль, шерсть и применяйте назначенные ингаляторы.',
    'diseases.data.respiratory.2.name': 'Бронхит',
    'diseases.data.respiratory.2.symptoms': 'Кашель с мокротой, усталость, небольшая температура',
    'diseases.data.respiratory.2.treatment': 'Используйте прохладный увлажнитель воздуха и обильное питье для разжижения мокроты. Если кашель длится более 2-3 недель - к врачу.',
    'diseases.data.skin.1.name': 'Экзема',
    'diseases.data.skin.1.symptoms': 'Сухие, зудящие, красные пятна на коже',
    'diseases.data.skin.1.treatment': 'Наносите густые эмоленты сразу после купания. При обострениях применяйте топические стероиды по назначению. Избегайте агрессивного мыла.',
    'diseases.data.skin.2.name': 'Ветрянка',
    'diseases.data.skin.2.symptoms': 'Зудящая сыпь с волдырями, температура',
    'diseases.data.skin.2.treatment': 'Каламиновый лосьон и овсяные ванночки для снятия зуда. Коротко стригите ногти. При лихорадке давайте парацетамол (не аспирин).',
    'diseases.data.allergies.1.name': 'Сезонная аллергия',
    'diseases.data.allergies.1.symptoms': 'Чихание, насморк, зуд в глазах',
    'diseases.data.allergies.1.treatment': 'Антигистаминные препараты 2-го поколения, используйте фильтры HEPA. В сезон пыльцы держите окна закрытыми.',
    
    'qa.title': 'Медицинский ИИ-Помощник',
    'qa.subtitle': 'Задавайте любые вопросы о здоровье детей и заболеваниях.',
    'qa.placeholder': 'Напишите свой вопрос здесь...',
    'qa.send': 'Отправить',
    'qa.error.empty': 'Извините, информация не найдена.',
    'qa.error.connect': 'Ошибка подключения к ИИ-ассистенту. Пожалуйста, попробуйте позже.',
    'qa.disclaimer': '(Я говорю на туркменском, русском, английском, немецком и корейском языках)',
    'qa.thinking': 'Думает...', 'qa.assistant': 'Ассистент',
    'tuina.header.subtitle': 'Туйна - это древняя китайская лечебная успокаивающая массажная техника для восстановления баланса.',
    'tuina.benefits.1': 'Улучшает кровообращение и способствует расслаблению.',
    'tuina.benefits.2': 'Снимает мышечное напряжение и боль в суставах.',
    'tuina.benefits.3': 'Снимает стресс и тревожность.',
    'tuina.benefits.4': 'Помогает при проблемах с пищеварением и дыханием у детей.',
    'tuina.benefits.5': 'Улучшает гибкость.',
    'tuina.techniques.title': 'Основные техники Туйна',
    'tuina.tech.1.title': 'Разминание',
    'tuina.tech.1.desc': 'Круговые движения пальцами для расслабления мышц.',
    'tuina.tech.2.title': 'Скручивание (Накатывание)',
    'tuina.tech.2.desc': 'Плавные накатывающие движения по позвоночнику для снятия усталости.',
    'tuina.tech.3.title': 'Надавливание',
    'tuina.tech.3.desc': 'Прямое давление на акупунктурные точки для стимуляции энергии.',
    'tuina.steps.title2': 'Как проводить массаж Туйна: Пошагово',
    'tuina.step2.1': 'Шаг 1: Положите ребенка удобно на спину.',
    'tuina.step2.2': 'Шаг 2: Начните с легких массажных движений плеч.',
    'tuina.step2.3': 'Шаг 3: Используйте накатывание по спине чтобы снять напряжение.',
    'tuina.step2.4': 'Шаг 4: Надавливайте на ключевые точки на меридианах.',
    'tuina.step2.5': 'Шаг 5: Завершите мягким поглаживанием.',
    'tuina.whentouse.title': 'Показания к Туйна массажу',
    'tuina.whentouse.intro': 'Туйна массаж эффективен при следующих состояниях:',
    'tuina.whentouse.1': 'Пищеварительные проблемы: колики, запоры.',
    'tuina.whentouse.2': 'Дыхательные: кашель, астма.',
    'tuina.whentouse.3': 'Мышечные боли, зажимы.',
    'tuina.whentouse.4': 'Стресс и плохой сон.',
    'tuina.children.title': 'Туйна для детей',
    'tuina.children.desc': 'Массаж Туйна легко адаптируется для детей с помощью очень мягких нажатий, помогает в лечении без лекарств.',
    'tuina.video.title': 'Смотреть видеоурок',
    'tuina.faq.title': 'Частые вопросы (FAQ)',
    'tuina.faq.1.q': 'Это безопасно?',
    'tuina.faq.1.a': 'Да, Туйна безопасен при выполнении обученным специалистом.',
    'tuina.faq.2.q': 'Сколько длится сеанс?',
    'tuina.faq.2.a': 'Для детей обычно от 15 до 30 минут.',
    'tuina.faq.3.q': 'Чего ожидать родителям?',
    'tuina.faq.3.a': 'Расслабления ребенка, улучшения сна, настроения.',
    'tuina.body.title': 'Части тела и техники',
    'tuina.body.1.title': '1. Голова и лицо',
    'tuina.body.1.how': 'Как выполнять: Лоб: Кончиками пальцев мягко массируйте лоб мелкими круговыми движениями. Виски: Слегка массируйте виски круговыми движениями. Вокруг глаз: Мягко надавливайте вокруг глаз и бровей для снятия напряжения.',
    'tuina.body.1.benefits': 'Польза: Снимает головные боли, уменьшает усталость глаз и успокаивает ребенка.',
    'tuina.body.1.when': 'Когда выполнять: Перед сном для расслабления. После экрана или стресса для снятия усталости глаз.',
    'tuina.body.2.title': '2. Шея и плечи',
    'tuina.body.2.how': 'Как выполнять: Шея: Большими пальцами мягко нажимайте и массируйте мышцы шеи. Плечи: Делайте мягкие круговые движения ладонями по плечевым мышцам.',
    'tuina.body.2.benefits': 'Польза: Снимает напряжение в шее и плечах, улучшает осанку и снимает стресс.',
    'tuina.body.2.when': 'Когда выполнять: После долгого сидения или игр. Когда ребенок напряжен или испытывает стресс.',
    'tuina.body.3.title': '3. Руки и кисти',
    'tuina.body.3.how': 'Как выполнять: Руки: Поглаживайте предплечья вверх-вниз легкими движениями. Кисти: Мягко массируйте ладони и пальцы большими пальцами круговыми движениями.',
    'tuina.body.3.benefits': 'Польза: Улучшает кровообращение, повышает гибкость и снимает напряжение в руках.',
    'tuina.body.3.when': 'Когда выполнять: После письма или использования устройств. До или после спорта для гибкости.',
    'tuina.body.4.title': '4. Спина и позвоночник',
    'tuina.body.4.how': 'Как выполнять: Позвоночник: Мягко массируйте вдоль позвоночника от шеи до поясницы кончиками пальцев. Поясница: Слегка надавливайте на поясницу и массируйте круговыми движениями ладоней.',
    'tuina.body.4.benefits': 'Польза: Снимает боли в спине, улучшает осанку и способствует расслаблению.',
    'tuina.body.4.when': 'Когда выполнять: После физических нагрузок или игр. После долгого сидения для снятия напряжения.',
    'tuina.body.5.title': '5. Ноги и стопы',
    'tuina.body.5.how': 'Как выполнять: Стопы: Мягко массируйте подошвы и пальцы ног большими пальцами круговыми движениями. Ноги: Поглаживайте ноги от стоп до бедер. Слегка надавливайте на икры и бедра.',
    'tuina.body.5.benefits': 'Польза: Снимает спазмы ног, улучшает кровообращение и способствует здоровому росту.',
    'tuina.body.5.when': 'Когда выполнять: До или после спорта. Перед сном для расслабления и улучшения сна.',
    'tuina.timing.title': 'Когда следует делать массаж Туйна?',
    'tuina.timing.daily': 'Ежедневное использование: Туйна можно делать ежедневно для поддержания расслабления и здоровья.',
    'tuina.timing.special': 'Особые случаи: После физических нагрузок. Когда ребенок напряжен, испытывает стресс или мышечные боли. Для помощи при проблемах со сном, головных болях или расстройствах пищеварения.',
    'tuina.keybenefits.title': 'Ключевые преимущества массажа Туйна для детей',
    'tuina.keybenefits.health': 'Польза для здоровья: Улучшает кровообращение, поддерживает иммунную функцию и общее здоровье.',
    'tuina.keybenefits.relieves': 'Облегчает частые проблемы: Снимает мышечное напряжение, стресс, головные боли и проблемы с пищеварением.',
    'tuina.keybenefits.sleep': 'Улучшает сон: Способствует расслаблению и помогает детям лучше спать.',

    'footer.text': '© 2026 Здоровые Дети. Все права защищены. Внимание: сайт носит информационный характер и не заменяет консультацию врача.',
  },
  en: {
    'nav.home': 'Home',
    'nav.tuina': 'Tuina Massage',
    'nav.diseases': 'Diseases',
    'nav.ai_qna': 'AI Q&A',
    'lang.select': 'Select Language',
    'app.title': 'Sagdyn Çagalar',
    'app.subtitle': 'A reliable platform for child health and care',
    
    'home.hero.title': 'Your Child’s Health is Our Priority',
    'home.hero.subtitle': 'A comprehensive health platform with pediatric medical information, a Tuina massage guide, and an AI assistant.',
    'home.hero.cta': 'Learn More',
    'home.features.title': 'Our Features',
    'home.feature.tuina.title': 'Tuina Massage',
    'home.feature.tuina.desc': 'Ancient Chinese Tuina massage techniques to improve children\'s immunity and health.',
    'home.feature.diseases.title': 'Pediatric Diseases',
    'home.feature.diseases.desc': 'Reliable information on all types of childhood diseases, symptoms, and treatments.',
    'home.feature.ai.title': 'AI Assistant',
    'home.feature.ai.desc': 'Ask any question about your child\'s health and get an instant response from AI.',
    
    'tuina.title': 'Tuina Massage Guide',
    'tuina.intro.title': 'What is Tuina massage?',
    'tuina.intro.desc': 'Tuina is a branch of Traditional Chinese Medicine involving massage of specific acupoints on a child\'s body to treat illnesses and boost immunity.',
    'tuina.history.title': 'History and Origins',
    'tuina.history.desc': 'Tuina massage has been a core component of Traditional Chinese Medicine (TCM) for over 2,000 years. It focuses on regulating the flow of "Qi" (vital energy) in the body and enhancing natural healing capabilities. The specialized pediatric form was refined during the Ming Dynasty (1368–1644).',
    'tuina.science.title': 'Scientific Support',
    'tuina.science.desc': 'Modern scientific research demonstrates that Tuina massage reduces pain in children, lowers stress hormones, and helps strengthen the immune system. Clinical trials show this method is particularly effective in alleviating cough and asthma symptoms.',
    'tuina.testimonial.title': 'Parent Testimonials',
    'tuina.testimonial.1.text': '"After learning Tuina massage, my child\'s sleep schedule completely improved. He sleeps peacefully through the night without waking up."',
    'tuina.testimonial.1.author': '— Aygul S., mother of a 2-year-old',
    'tuina.testimonial.2.text': '"We suffered a lot from intestinal colic. Once we started daily abdominal massage, my baby relaxed and the crying decreased significantly."',
    'tuina.testimonial.2.author': '— Merdan K., father of a 6-month-old',
    'tuina.areas.title': 'Organs and Their Benefits',
    'tuina.areas.desc': 'Tuina massage affects specific organs of the child, improving their normal functioning.',
    'tuina.organ.1.name': 'Stomach and Intestines',
    'tuina.organ.1.benefit': 'Improves digestion, relieves colic, increases appetite.',
    'tuina.organ.2.name': 'Lungs and Respiration',
    'tuina.organ.2.benefit': 'Treats colds, coughs, and makes breathing easier.',
    'tuina.organ.3.name': 'Kidneys and Nervous System',
    'tuina.organ.3.benefit': 'Improves sleep quality, restores natural immunity.',
    'tuina.steps.title': 'Step-by-step Massage Technique',
    'tuina.step.1.title': '1. Abdominal massage for digestion',
    'tuina.step.1.desc': 'Lay the child on their back. Gently stroke the abdomen in circular clockwise motions around the navel (3-5 minutes). This eases digestion and relieves pain.',
    'tuina.step.2.title': '2. Chest and back massage for lungs',
    'tuina.step.2.desc': 'Stroke the chest from the center outwards with your palm. Then gently massage the back between the shoulder blades up and down (do not press on the bones).',
    'tuina.step.3.title': '3. Spinal massage for immunity',
    'tuina.step.3.desc': 'With your fingertips, stroke along the spine from bottom to top. Gently press the center of the child\'s palms and soles with your thumb.',
    'tuina.benefits.title': 'Health Benefits',
    'tuina.benefit.1': 'Naturally boosts the immune system.',
    'tuina.benefit.2': 'Improves digestion and promotes deeper sleep.',
    'tuina.benefit.3': 'Relieves fever, cough, and common cold symptoms.',
    
    'diseases.title': 'Pediatric Diseases Library',
    'diseases.fever': 'Fever & Infections',
    'diseases.respiratory': 'Respiratory Diseases',
    'diseases.skin': 'Skin Diseases',
    'diseases.digestive': 'Digestive Issues',
    'diseases.allergies': 'Allergies',
    'diseases.category_select': 'Select a category',
    'diseases.category_select_desc': 'to view diseases and treatments',
    'diseases.categories.title': 'Categories',
    'diseases.categories.desc': 'Choose a category below to explore common pediatric conditions, their symptoms, and suggested home care.',
    'diseases.info.soon': 'Information will be added soon',
    'diseases.label.symptoms': 'Symptoms',
    'diseases.label.treatment': 'Treatment / Home Care',
    'diseases.data.fever.1.name': 'Common Cold',
    'diseases.data.fever.1.symptoms': 'Runny nose, low fever, cough',
    'diseases.data.fever.1.treatment': 'Ensure hydration and rest. Use saline drops for congestion. Avoid OTC cough medicines for children under 4 without consulting a pediatrician.',
    'diseases.data.fever.2.name': 'Flu (Influenza)',
    'diseases.data.fever.2.symptoms': 'High fever, body aches, fatigue',
    'diseases.data.fever.2.treatment': 'Administer pediatrician-approved antipyretics like acetaminophen. Seek immediate care for any respiratory distress or unusual lethargy.',
    'diseases.data.digestive.1.name': 'Gastroenteritis',
    'diseases.data.digestive.1.symptoms': 'Vomiting, diarrhea, stomach pain',
    'diseases.data.digestive.1.treatment': 'Prioritize oral rehydration solutions (ORS) in frequent, small amounts. Gradually introduce a bland (BRAT) diet. Avoid dairy and sugary drinks.',
    'diseases.data.respiratory.1.name': 'Asthma',
    'diseases.data.respiratory.1.symptoms': 'Wheezing, shortness of breath, chest tightness',
    'diseases.data.respiratory.1.treatment': 'Strictly follow prescribed Asthma Action Plan. Use short-acting inhalers for flare-ups. Mitigate environmental triggers like dust and pet dander.',
    'diseases.data.respiratory.2.name': 'Bronchitis',
    'diseases.data.respiratory.2.symptoms': 'Cough with mucus, fatigue, mild fever',
    'diseases.data.respiratory.2.treatment': 'Use a cool-mist humidifier and high fluid intake to thin mucus. Consult a doctor if the cough persists beyond 2-3 weeks or worsens.',
    'diseases.data.skin.1.name': 'Eczema',
    'diseases.data.skin.1.symptoms': 'Dry, itchy, red patches on skin',
    'diseases.data.skin.1.treatment': 'Apply unscented, thick emollients immediately after brief baths. Use prescribed topical corticosteroids during active flare-ups.',
    'diseases.data.skin.2.name': 'Chickenpox',
    'diseases.data.skin.2.symptoms': 'Itchy rash with blisters, fever, fatigue',
    'diseases.data.skin.2.treatment': 'Apply calamine lotion or oatmeal baths for itch. Keep fingernails trimmed to prevent secondary bacterial infections. Administer acetaminophen (strictly avoid aspirin).',
    'diseases.data.allergies.1.name': 'Seasonal Allergies',
    'diseases.data.allergies.1.symptoms': 'Sneezing, runny nose, itchy eyes',
    'diseases.data.allergies.1.treatment': 'Administer non-sedating, second-generation antihistamines. Utilize HEPA air purifiers and keep windows closed during high pollen seasons.',
    
    'qa.title': 'AI Medical Assistant',
    'qa.subtitle': 'Ask anything about child health, diseases, or care.',
    'qa.placeholder': 'Type your question here...',
    'qa.send': 'Send',
    'qa.error.empty': 'Sorry, no information found.',
    'qa.error.connect': 'Error connecting to the AI assistant. Please try again later.',
    'qa.disclaimer': '(I can speak Turkmen, Russian, English, German, and Korean)',
    'qa.thinking': 'Thinking...', 'qa.assistant': 'Assistant',
    'tuina.header.subtitle': 'Tuina is an ancient Chinese therapeutic massage technique that focuses on restoring balance and healing.',
    'tuina.benefits.1': 'Improves circulation and promotes relaxation.',
    'tuina.benefits.2': 'Alleviates muscle tension and joint pain.',
    'tuina.benefits.3': 'Relieves stress and anxiety.',
    'tuina.benefits.4': 'Helps with digestive and respiratory problems in children.',
    'tuina.benefits.5': 'Improves flexibility and range of motion.',
    'tuina.techniques.title': 'Common Tuina Techniques',
    'tuina.tech.1.title': 'Kneading',
    'tuina.tech.1.desc': 'Uses circular movements with the fingers to relax muscles and improve blood flow.',
    'tuina.tech.2.title': 'Rolling',
    'tuina.tech.2.desc': 'Gentle rolling movements along the limbs or spine to relieve stiffness and tension.',
    'tuina.tech.3.title': 'Pressing',
    'tuina.tech.3.desc': 'Applying direct pressure on key acupoints to stimulate energy flow and relieve pain.',
    'tuina.steps.title2': 'How to Perform Tuina Massage: Step-by-Step',
    'tuina.step2.1': 'Step 1: Start by having the child or patient lie comfortably on their back.',
    'tuina.step2.2': 'Step 2: Begin with gentle, circular kneading motions on the shoulders to relax the muscles.',
    'tuina.step2.3': 'Step 3: Use rolling motions on the back and spine to release tension.',
    'tuina.step2.4': 'Step 4: Apply light pressure on acupoints along the meridians to restore balance.',
    'tuina.step2.5': 'Step 5: End with soft, smooth strokes to calm the body and mind.',
    'tuina.whentouse.title': 'When to Use Tuina Massage',
    'tuina.whentouse.intro': 'Tuina is effective for children and adults alike in treating:',
    'tuina.whentouse.1': 'Digestive issues like constipation or bloating.',
    'tuina.whentouse.2': 'Respiratory conditions like asthma and cough.',
    'tuina.whentouse.3': 'Muscle pain, stiffness, and joint issues.',
    'tuina.whentouse.4': 'Stress relief, relaxation, and improving sleep quality.',
    'tuina.children.title': 'Tuina for Children',
    'tuina.children.desc': 'Tuina can be adapted for young children, offering gentle pressure and soothing techniques tailored to their needs. It is especially helpful for managing discomfort in children without the use of medications.',
    'tuina.video.title': 'Watch the Video Tutorial',
    'tuina.faq.title': 'Frequently Asked Questions',
    'tuina.faq.1.q': 'Is it safe?',
    'tuina.faq.1.a': 'Yes, Tuina is generally safe when performed by a trained professional, and is adapted to be very gentle for children.',
    'tuina.faq.2.q': 'How long does a session last?',
    'tuina.faq.2.a': 'A typical pediatric session lasts 15-30 minutes depending on the child\'s age and condition.',
    'tuina.faq.3.q': 'What can parents expect?',
    'tuina.faq.3.a': 'Parents can expect their child to feel more relaxed and rested. It acts as a complementary therapy alongside conventional pediatric care.',
    
    'tuina.body.title': 'Body Parts and Techniques',
    'tuina.body.1.title': '1. Head and Face',
    'tuina.body.1.how': 'How to Perform It: Forehead: Use your fingers to rub gently in small circular motions on the forehead. Temples: Lightly massage in circles on both temples. Around the Eyes: Gently press around the eyes and eyebrows to relieve tension.',
    'tuina.body.1.benefits': 'Benefits: Relieves headaches, reduces eye strain, and helps calm the child.',
    'tuina.body.1.when': 'When to Do It: Before bedtime to help the child relax. After screen time or any stressful activity to ease eye strain and stress.',
    
    'tuina.body.2.title': '2. Neck and Shoulders',
    'tuina.body.2.how': 'How to Perform It: Neck: Use your thumbs to gently press and massage the muscles along the neck. Shoulders: Apply gentle circular motions on the shoulder muscles with your palms.',
    'tuina.body.2.benefits': 'Benefits: Reduces tension in the neck and shoulders, helps with posture, and relieves stress.',
    'tuina.body.2.when': 'When to Do It: After long periods of sitting or playing. When the child feels tense or stressed.',

    'tuina.body.3.title': '3. Arms and Hands',
    'tuina.body.3.how': 'How to Perform It: Arms: Rub up and down the forearms with light strokes. Hands: Massage the palms and fingers gently with your thumbs, using circular motions.',
    'tuina.body.3.benefits': 'Benefits: Improves circulation, enhances flexibility, and reduces tension in the hands.',
    'tuina.body.3.when': 'When to Do It: After writing or using devices. Before or after sports to help with flexibility.',

    'tuina.body.4.title': '4. Back and Spine',
    'tuina.body.4.how': 'How to Perform It: Spine: Gently massage along the spine, moving from the neck to the lower back with your thumbs or fingertips. Lower Back: Apply light pressure on the lower back and gently move your palms in circular motions.',
    'tuina.body.4.benefits': 'Benefits: Relieves back pain, helps improve posture, and promotes relaxation.',
    'tuina.body.4.when': 'When to Do It: After physical activities like sports or play. After long sitting periods to reduce tension in the back.',

    'tuina.body.5.title': '5. Legs and Feet',
    'tuina.body.5.how': 'How to Perform It: Feet: Massage the soles and toes gently with your thumbs, using small circles. Legs: Use long strokes to massage from the feet to the thighs. Gently press on the calves and thighs.',
    'tuina.body.5.benefits': 'Benefits: Reduces leg cramps, improves blood circulation, and supports healthy growth.',
    'tuina.body.5.when': 'When to Do It: Before or after physical activities like running or playing sports. Before bedtime to help the child relax and sleep better.',

    'tuina.timing.title': 'When Should Tuina Massage Be Done?',
    'tuina.timing.daily': 'Daily Use: Tuina can be performed daily to maintain relaxation and promote overall health.',
    'tuina.timing.special': 'Special Times: After physical activities like sports or play. When the child feels stressed, tense, or has muscle pain. To help with sleep issues, headaches, or digestive discomfort.',

    'tuina.keybenefits.title': 'Key Benefits of Tuina Massage for Children',
    'tuina.keybenefits.health': 'Health Benefits: Helps with blood circulation, supports immune function, and improves overall health.',
    'tuina.keybenefits.relieves': 'Relieves Common Problems: Eases muscle tension, stress, headaches, and digestive issues.',
    'tuina.keybenefits.sleep': 'Improves Sleep: Promotes relaxation and helps children sleep better.',

    'footer.text': '© 2026 Sagdyn Çagalar. All rights reserved. Disclaimer: This website is for informational purposes only and does not replace professional medical advice.',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.tuina': 'Tuina Massage',
    'nav.diseases': 'Krankheiten',
    'nav.ai_qna': 'KI Fragen & Antworten',
    'lang.select': 'Sprache Auswählen',
    'app.title': 'Sagdyn Çagalar',
    'app.subtitle': 'Eine zuverlässige Plattform für Kindergesundheit und -pflege',
    
    'home.hero.title': 'Die Gesundheit Ihres Kindes ist unsere Priorität',
    'home.hero.subtitle': 'Eine umfassende Gesundheitsplattform mit pädiatrischen medizinischen Informationen, einem Tuina-Massage-Guide und einem KI-Assistenten.',
    'home.hero.cta': 'Mehr erfahren',
    'home.features.title': 'Unsere Funktionen',
    'home.feature.tuina.title': 'Tuina Massage',
    'home.feature.tuina.desc': 'Alte chinesische Tuina-Massagetechniken zur Verbesserung der Immunität und der Gesundheit von Kindern.',
    'home.feature.diseases.title': 'Kinderkrankheiten',
    'home.feature.diseases.desc': 'Zuverlässige Krankheiten zu allen Arten von Kinderkrankheiten, Symptomen und Behandlungen.',
    'home.feature.ai.title': 'KI-Assistent',
    'home.feature.ai.desc': 'Stellen Sie eine beliebige Frage zur Gesundheit Ihres Kindes und erhalten Sie sofort eine Antwort von der KI.',
    
    'tuina.title': 'Tuina Massage Guide',
    'tuina.intro.title': 'Was ist Tuina Massage?',
    'tuina.intro.desc': 'Tuina ist ein Zweig der Traditionellen Chinesischen Medizin, der die Massage bestimmter Akupunkturpunkte am Körper eines Kindes umfasst, um Krankheiten zu behandeln und das Immunsystem zu stärken.',
    'tuina.history.title': 'Geschichte und Ursprünge',
    'tuina.history.desc': 'Die Tuina-Massage ist seit über 2.000 Jahren ein zentraler Bestandteil der Traditionellen Chinesischen Medizin (TCM). Sie zielt darauf ab, den Fluss des „Qi“ (Lebensenergie) im Körper zu regulieren und die natürlichen Heilkräfte zu stärken. Die spezielle pädiatrische Form wurde während der Ming-Dynastie (1368–1644) weiterentwickelt.',
    'tuina.science.title': 'Wissenschaftliche Unterstützung',
    'tuina.science.desc': 'Moderne wissenschaftliche Untersuchungen zeigen, dass die Tuina-Massage Schmerzen bei Kindern lindert, Stresshormone senkt und das Immunsystem stärkt. Klinische Studien belegen, dass diese Methode besonders bei Husten und Asthmasymptomen wirksam ist.',
    'tuina.testimonial.title': 'Erfahrungsberichte',
    'tuina.testimonial.1.text': '"Nachdem ich die Tuina-Massage erlernt hatte, verbesserte sich der Schlafrhythmus meines Kindes völlig. Er schläft nachts friedlich durch."',
    'tuina.testimonial.1.author': '— Aygul S., Mutter eines 2-Jährigen',
    'tuina.testimonial.2.text': '"Wir litten sehr unter Darmkoliken. Seit wir täglich eine Bauchmassage durchführen, ist mein Baby entspannter und weint viel weniger."',
    'tuina.testimonial.2.author': '— Merdan K., Vater einer 6 Monate alten Tochter',
    'tuina.areas.title': 'Organe und ihre Vorteile',
    'tuina.areas.desc': 'Die Tuina-Massage wirkt auf bestimmte Organe des Kindes und verbessert deren normale Funktion.',
    'tuina.organ.1.name': 'Magen und Darm',
    'tuina.organ.1.benefit': 'Verbessert die Verdauung, lindert Koliken, steigert den Appetit.',
    'tuina.organ.2.name': 'Lunge und Atmung',
    'tuina.organ.2.benefit': 'Behandelt Erkältungen, Husten und erleichtert das Atmen.',
    'tuina.organ.3.name': 'Nieren und Nervensystem',
    'tuina.organ.3.benefit': 'Verbessert die Schlafqualität, stellt die natürliche Immunität wieder her.',
    'tuina.steps.title': 'Schritt-für-Schritt Massagetechnik',
    'tuina.step.1.title': '1. Bauchmassage für die Verdauung',
    'tuina.step.1.desc': 'Legen Sie das Kind auf den Rücken. Streichen Sie den Bauch sanft in kreisenden Bewegungen im Uhrzeigersinn um den Bauchnabel (3-5 Minuten). Das erleichtert die Verdauung und lindert Schmerzen.',
    'tuina.step.2.title': '2. Brust- und Rückenmassage für die Lunge',
    'tuina.step.2.desc': 'Streichen Sie mit der Handfläche von der Mitte der Brust nach außen. Massieren Sie dann sanft den Rücken zwischen den Schulterblättern auf und ab (nicht auf die Knochen drücken).',
    'tuina.step.3.title': '3. Wirbelsäulenmassage für das Immunsystem',
    'tuina.step.3.desc': 'Streichen Sie mit den Fingerspitzen entlang der Wirbelsäule von unten nach oben. Drücken Sie sanft mit dem Daumen auf die Mitte der Handflächen und Fußsohlen des Kindes.',
    'tuina.benefits.title': 'Gesundheitliche Vorteile',
    'tuina.benefit.1': 'Stärkt das Immunsystem auf natürliche Weise.',
    'tuina.benefit.2': 'Verbessert die Verdauung und die Schlafqualität.',
    'tuina.benefit.3': 'Lindert Fieber, Husten und Erkältungssymptome.',
    
    'diseases.title': 'Kinderkrankheiten-Bibliothek',
    'diseases.fever': 'Fieber & Infektionen',
    'diseases.respiratory': 'Atemwegserkrankungen',
    'diseases.skin': 'Hautkrankheiten',
    'diseases.digestive': 'Verdauungsprobleme',
    'diseases.allergies': 'Allergien',
    'diseases.category_select': 'Kategorie auswählen',
    'diseases.category_select_desc': 'um Krankheiten und Behandlungen anzuzeigen',
    'diseases.categories.title': 'Kategorien',
    'diseases.categories.desc': 'Wählen Sie unten eine Kategorie aus, um häufige pädiatrische Erkrankungen, ihre Symptome und empfohlene häusliche Pflege zu erkunden.',
    'diseases.info.soon': 'Informationen werden bald hinzugefügt',
    'diseases.label.symptoms': 'Symptome',
    'diseases.label.treatment': 'Behandlung / Hausmittel',
    'diseases.data.fever.1.name': 'Erkältung',
    'diseases.data.fever.1.symptoms': 'Laufende Nase, leichtes Fieber, Husten',
    'diseases.data.fever.1.treatment': 'Sorgen Sie für ausreichend Flüssigkeit und Ruhe. Verwenden Sie Kochsalz-Nasenspray. Keine rezeptfreien Hustenmittel für Kinder unter 4 Jahren ohne Arzt.',
    'diseases.data.fever.2.name': 'Grippe (Influenza)',
    'diseases.data.fever.2.symptoms': 'Hohes Fieber, Gliederschmerzen, Müdigkeit',
    'diseases.data.fever.2.treatment': 'Fiebersenkende Mittel nach Absprache mit Arzt. Strenge Flüssigkeitszufuhr. Bei Atemnot oder Lethargie sofort ärztliche Hilfe suchen.',
    'diseases.data.digestive.1.name': 'Magen-Darm-Entzündung',
    'diseases.data.digestive.1.symptoms': 'Erbrechen, Durchfall, Bauchschmerzen',
    'diseases.data.digestive.1.treatment': 'Orale Rehydratisierungslösungen (ORS) in kleinen Schlucken. Langsam Schonkost einführen. Milchprodukte und zuckerhaltige Getränke meiden.',
    'diseases.data.respiratory.1.name': 'Asthma',
    'diseases.data.respiratory.1.symptoms': 'Keuchen, Kurzatmigkeit, Engegefühl in der Brust',
    'diseases.data.respiratory.1.treatment': 'Strikt den Asthma-Aktionsplan befolgen. Notfallinhalatoren bei akuten Schüben verwenden. Auslöser wie Staub und Tierhaare meiden.',
    'diseases.data.respiratory.2.name': 'Bronchitis',
    'diseases.data.respiratory.2.symptoms': 'Husten mit Schleim, Müdigkeit, leichtes Fieber',
    'diseases.data.respiratory.2.treatment': 'Kaltluftbefeuchter und viel Flüssigkeit zur Schleimlösung einsetzen. Bei Husten länger als 2-3 Wochen einen Arzt konsultieren.',
    'diseases.data.skin.1.name': 'Ekzem',
    'diseases.data.skin.1.symptoms': 'Trockene, juckende, rote Flecken auf der Haut',
    'diseases.data.skin.1.treatment': 'Unparfümierte Emollienzien nach Bädern auftragen. Bei Schüben verschriebene topische Kortikosteroide verwenden. Aggressive Seifen meiden.',
    'diseases.data.skin.2.name': 'Windpocken',
    'diseases.data.skin.2.symptoms': 'Juckender Ausschlag mit Blasen, Fieber',
    'diseases.data.skin.2.treatment': 'Calamin-Lotion und Haferflockenbäder gegen Juckreiz. Fingernägel kurz halten, um Infektionen zu vermeiden. Paracetamol bei Fieber (kein Aspirin).',
    'diseases.data.allergies.1.name': 'Saisonale Allergien',
    'diseases.data.allergies.1.symptoms': 'Niesen, laufende Nase, juckende Augen',
    'diseases.data.allergies.1.treatment': 'Nicht sedierende Antihistaminika verwenden. HEPA-Luftreiniger einsetzen und während des Pollenflugs Fenster geschlossen halten.',
    
    'qa.title': 'Medizinischer KI-Assistent',
    'qa.subtitle': 'Erhalten Sie Antworten auf alle Fragen zur Gesundheit.',
    'qa.placeholder': 'Geben Sie hier Ihre Frage ein...',
    'qa.send': 'Senden',
    'qa.error.empty': 'Entschuldigung, keine Informationen gefunden.',
    'qa.error.connect': 'Fehler bei der Verbindung zum KI-Assistenten. Bitte versuchen Sie es später erneut.',
    'qa.disclaimer': '(Ich spreche Turkmenisch, Russisch, Englisch, Deutsch und Koreanisch)',
    'qa.thinking': 'Denkt nach...', 'qa.assistant': 'Assistent',
    'tuina.header.subtitle': 'Tuina ist eine alte chinesische therapeutische Massagetechnik, die sich auf die Wiederherstellung des Gleichgewichts und die Heilung konzentriert.',
    'tuina.benefits.1': 'Verbessert die Durchblutung und fördert die Entspannung.',
    'tuina.benefits.2': 'Lindert Muskelverspannungen und Gelenkschmerzen.',
    'tuina.benefits.3': 'Baut Stress und Angstzustände ab.',
    'tuina.benefits.4': 'Hilft bei Verdauungs- und Atemproblemen bei Kindern.',
    'tuina.benefits.5': 'Verbessert Flexibilität und Beweglichkeit.',
    'tuina.techniques.title': 'Gängige Tuina-Techniken',
    'tuina.tech.1.title': 'Kneten',
    'tuina.tech.1.desc': 'Verwendet kreisende Bewegungen mit den Fingern, um die Muskeln zu entspannen und die Durchblutung zu verbessern.',
    'tuina.tech.2.title': 'Rollen',
    'tuina.tech.2.desc': 'Sanfte Rollbewegungen entlang der Gliedmaßen oder der Wirbelsäule, um Steifheit und Verspannungen zu lösen.',
    'tuina.tech.3.title': 'Drücken',
    'tuina.tech.3.desc': 'Direkter Druck auf wichtige Akupunkturpunkte zur Stimulierung des Energieflusses und zur Schmerzlinderung.',
    'tuina.steps.title2': 'Durchführung der Tuina-Massage: Schritt für Schritt',
    'tuina.step2.1': 'Schritt 1: Beginnen Sie damit, dass das Kind oder der Patient bequem auf dem Rücken liegt.',
    'tuina.step2.2': 'Schritt 2: Beginnen Sie mit sanften, kreisenden Knetbewegungen auf den Schultern.',
    'tuina.step2.3': 'Schritt 3: Verwenden Sie Rollbewegungen auf dem Rücken und der Wirbelsäule, um Verspannungen zu lösen.',
    'tuina.step2.4': 'Schritt 4: Üben Sie leichten Druck auf die Akupunkturpunkte entlang der Meridiane aus.',
    'tuina.step2.5': 'Schritt 5: Beenden Sie mit sanften, gleichmäßigen Strichen, um Körper und Geist zu beruhigen.',
    'tuina.whentouse.title': 'Wann Tuina-Massage angewendet wird',
    'tuina.whentouse.intro': 'Tuina ist sowohl bei Kindern als auch bei Erwachsenen wirksam zur Behandlung von:',
    'tuina.whentouse.1': 'Verdauungsprobleme wie Verstopfung oder Blähungen.',
    'tuina.whentouse.2': 'Atemwegserkrankungen wie Asthma und Husten.',
    'tuina.whentouse.3': 'Muskelschmerzen, Steifheit und Gelenkprobleme.',
    'tuina.whentouse.4': 'Stressabbau, Entspannung und Verbesserung der Schlafqualität.',
    'tuina.children.title': 'Tuina für Kinder',
    'tuina.children.desc': 'Tuina kann für kleine Kinder angepasst werden, indem sanfter Druck und beruhigende Techniken auf ihre Bedürfnisse abgestimmt werden.',
    'tuina.video.title': 'Video-Tutorial ansehen',
    'tuina.faq.title': 'Häufig gestellte Fragen',
    'tuina.faq.1.q': 'Ist es sicher?',
    'tuina.faq.1.a': 'Ja, Tuina ist im Allgemeinen sicher, wenn es von einem geschulten Fachmann durchgeführt wird.',
    'tuina.faq.2.q': 'Wie lange dauert eine Sitzung?',
    'tuina.faq.2.a': 'Eine typische pädiatrische Sitzung dauert 15-30 Minuten.',
    'tuina.faq.3.q': 'Was können Eltern erwarten?',
    'tuina.faq.3.a': 'Eltern können erwarten, dass sich ihr Kind entspannter und ausgeruhter fühlt.',
    'tuina.body.title': 'Körperteile und Techniken',
    'tuina.body.1.title': '1. Kopf und Gesicht',
    'tuina.body.1.how': 'Durchführung: Stirn: Mit den Fingern vorsichtig in kleinen kreisenden Bewegungen auf der Stirn reiben. Schläfen: Leicht in Kreisen an beiden Schläfen massieren. Um die Augen: Sanft um die Augen und Augenbrauen drücken, um Verspannungen zu lösen.',
    'tuina.body.1.benefits': 'Vorteile: Lindert Kopfschmerzen, reduziert die Belastung der Augen und hilft dem Kind, sich zu beruhigen.',
    'tuina.body.1.when': 'Wann: Vor dem Schlafengehen, um dem Kind zu helfen, sich zu entspannen. Nach dem Fernsehen oder stressigen Aktivitäten.',
    'tuina.body.2.title': '2. Nacken und Schultern',
    'tuina.body.2.how': 'Durchführung: Nacken: Mit den Daumen sanft drücken und die Muskeln entlang des Nackens massieren. Schultern: Mit den Handflächen sanfte kreisende Bewegungen auf den Schultermuskeln ausführen.',
    'tuina.body.2.benefits': 'Vorteile: Reduziert Verspannungen in Nacken und Schultern, hilft bei der Körperhaltung und baut Stress ab.',
    'tuina.body.2.when': 'Wann: Nach langem Sitzen oder Spielen. Wenn das Kind angespannt oder gestresst ist.',
    'tuina.body.3.title': '3. Arme und Hände',
    'tuina.body.3.how': 'Durchführung: Arme: Die Unterarme mit leichten Streichbewegungen auf- und abreiben. Hände: Die Handflächen und Finger sanft mit den Daumen in kreisenden Bewegungen massieren.',
    'tuina.body.3.benefits': 'Vorteile: Verbessert die Durchblutung, erhöht die Flexibilität und löst Verspannungen in den Händen.',
    'tuina.body.3.when': 'Wann: Nach dem Schreiben oder Verwenden von Geräten. Vor oder nach dem Sport.',
    'tuina.body.4.title': '4. Rücken und Wirbelsäule',
    'tuina.body.4.how': 'Durchführung: Wirbelsäule: Massieren Sie sanft entlang der Wirbelsäule vom Nacken zum unteren Rücken. Unterer Rücken: Üben Sie leichten Druck aus und bewegen Sie die Handflächen kreisförmig.',
    'tuina.body.4.benefits': 'Vorteile: Lindert Rückenschmerzen, fördert eine bessere Körperhaltung und Entspannung.',
    'tuina.body.4.when': 'Wann: Nach körperlichen Aktivitäten. Nach langem Sitzen, um Verspannungen im Rücken zu lösen.',
    'tuina.body.5.title': '5. Beine und Füße',
    'tuina.body.5.how': 'Durchführung: Füße: Massieren Sie die Fußsohlen und Zehen sanft mit Daumen. Beine: Streichen Sie von den Füßen zu den Oberschenkeln. Drücken Sie sanft auf Waden und Oberschenkel.',
    'tuina.body.5.benefits': 'Vorteile: Reduziert Beinkrämpfe, verbessert die Durchblutung und unterstützt ein gesundes Wachstum.',
    'tuina.body.5.when': 'Wann: Vor oder nach körperlichen Aktivitäten. Vor dem Schlafengehen.',
    'tuina.timing.title': 'Wann sollte die Tuina-Massage durchgeführt werden?',
    'tuina.timing.daily': 'Täglicher Gebrauch: Tuina kann täglich durchgeführt werden, um Entspannung und allgemeine Gesundheit zu erhalten.',
    'tuina.timing.special': 'Besondere Zeiten: Nach körperlichen Aktivitäten. Wenn das Kind gestresst ist oder Muskelschmerzen hat. Bei Schlafproblemen, Kopfschmerzen oder Verdauungsbeschwerden.',
    'tuina.keybenefits.title': 'Hauptvorteile der Tuina-Massage für Kinder',
    'tuina.keybenefits.health': 'Gesundheitliche Vorteile: Hilft bei der Durchblutung, unterstützt die Immunfunktion und verbessert die allgemeine Gesundheit.',
    'tuina.keybenefits.relieves': 'Lindert häufige Probleme: Löst Muskelverspannungen, Stress, Kopfschmerzen und Verdauungsprobleme.',
    'tuina.keybenefits.sleep': 'Verbessert den Schlaf: Fördert die Entspannung und hilft Kindern, besser zu schlafen.',

    'footer.text': '© 2026 Sagdyn Çagalar. Alle Rechte vorbehalten. Haftungsausschluss: Diese Website dient nur zu Informationszwecken.',
  },
  ko: {
    'nav.home': '홈',
    'nav.tuina': '추나 마사지',
    'nav.diseases': '질병',
    'nav.ai_qna': 'AI Q&A',
    'lang.select': '언어 선택',
    'app.title': '건강한 아이들 (Sagdyn Çagalar)',
    'app.subtitle': '아이들의 건강과 보살핌을 위한 신뢰할 수 있는 플랫폼',
    'home.hero.title': '아이의 건강이 우리의 최우선입니다',
    'home.hero.subtitle': '소아 의료 정보, 추나 마사지 가이드 및 AI 어시스턴트를 갖춘 포괄적인 건강 플랫폼.',
    'home.hero.cta': '더 알아보기',
    'home.features.title': '주요 기능',
    'home.feature.tuina.title': '추나 마사지',
    'home.feature.tuina.desc': '어린이의 면역력과 건강을 향상시키는 고대 중국의 추나 마사지 기술.',
    'home.feature.diseases.title': '소아 질병',
    'home.feature.diseases.desc': '모든 유형의 소아 질병, 증상 및 치료에 대한 신뢰할 수 있는 정보.',
    'home.feature.ai.title': 'AI 어시스턴트',
    'home.feature.ai.desc': '자녀의 건강에 대한 질문을 하고 AI로부터 즉각적인 답변을 받으세요.',
    'tuina.title': '추나 마사지 가이드',
    'tuina.intro.title': '추나 마사지란 무엇인가요?',
    'tuina.intro.desc': '추나는 어린이 신체의 특정 혈자리를 마사지하여 질병을 치료하고 면역력을 높이는 전통 중의학의 한 분야입니다.',
    'tuina.history.title': '역사와 기원',
    'tuina.history.desc': '추나 마사지는 2,000년 이상 전통 중의학(TCM)의 핵심 요소였습니다. 체내 \'기\'(생명 에너지)의 흐름을 조절하고 자연 치유력을 향상시키는 데 중점을 둡니다. 소아과에 특화된 형태는 명나라(1368–1644) 시대에 발전했습니다.',
    'tuina.science.title': '과학적 근거',
    'tuina.science.desc': '현대 과학 연구에 따르면 추나 마사지는 아이들의 통증을 줄여주고, 스트레스 호르몬을 낮추며, 면역 체계를 강화하는 데 도움을 줍니다. 임상 시험에 따르면 이 방법은 특히 기침과 천식 증상을 완화하는 데 효과적입니다.',
    'tuina.testimonial.title': '부모님 후기',
    'tuina.testimonial.1.text': '\'추나 마사지를 배운 후, 제 아이의 수면 패턴이 완전히 좋아졌습니다. 밤에 깨지 않고 평화롭게 잘 자게 되었습니다.\'',
    'tuina.testimonial.1.author': '— 아이굴 S., 2살 아이의 어머니',
    'tuina.testimonial.2.text': '\'우리는 장 영아 산통으로 많이 고생했습니다. 매일 복부 마사지를 시작하자마자 아기가 편안해졌고 우는 횟수가 크게 줄어들었습니다.\'',
    'tuina.testimonial.2.author': '— 메르단 K., 6개월 아기의 아버지',
    'tuina.areas.title': '장기와 그 효능',
    'tuina.areas.desc': '추나 마사지는 아이의 특정 장기에 작용하여 정상적인 기능 향상에 도움을 줍니다.',
    'tuina.organ.1.name': '위와 장',
    'tuina.organ.1.benefit': '소화를 개선하고 복통을 줄여주며 식욕을 증진시킵니다.',
    'tuina.organ.2.name': '폐와 호흡기',
    'tuina.organ.2.benefit': '감기와 기침을 완화하고 숨쉬기를 편안하게 해줍니다.',
    'tuina.organ.3.name': '신장과 신경계',
    'tuina.organ.3.benefit': '수면의 질을 높이고 자연 면역력을 회복시킵니다.',
    'tuina.steps.title': '단계별 마사지 기술',
    'tuina.step.1.title': '1. 소화를 위한 복부 마사지',
    'tuina.step.1.desc': '아이를 똑바로 눕히세요. 배꼽 주위를 시계 방향으로 둥글게 원형으로 살살 문지릅니다 (3-5분간). 소화를 돕고 복통을 줄여줍니다.',
    'tuina.step.2.title': '2. 폐를 위한 가슴과 등 마사지',
    'tuina.step.2.desc': '가슴 중앙에서 바깥쪽으로 손바닥을 이용해 문지릅니다. 그 후 등 쪽 날개뼈 사이를 위아래로 부드럽게 마사지합니다 (뼈를 누르지 않도록 주의).',
    'tuina.step.3.title': '3. 면역력을 위한 척추 마사지',
    'tuina.step.3.desc': '손끝으로 척추를 아래에서 위로 부드럽게 쓰다듬습니다. 엄지손가락으로 아이의 손바닥 중앙과 발바닥 중앙을 가볍게 누릅니다.',
    'tuina.benefits.title': '건강상의 이점',
    'tuina.benefit.1': '면역 체계를 자연스럽게 강화시킵니다.',
    'tuina.benefit.2': '소화를 돕고 깊은 수면을 유도합니다.',
    'tuina.benefit.3': '열, 기침, 감기 증상을 크게 완화시킵니다.',
    'diseases.title': '소아 질병 라이브러리',
    'diseases.fever': '발열 및 감염',
    'diseases.respiratory': '호흡기 질환',
    'diseases.skin': '피부 질환',
    'diseases.digestive': '소화기 질환',
    'diseases.allergies': '알레르기',
    'diseases.category_select': '카테고리 선택',
    'diseases.category_select_desc': '질병 및 치료법을 봅니다',
    'diseases.categories.title': '카테고리',
    'diseases.categories.desc': '일반적인 소아 질환, 증상 및 집에서의 케어 방법을 보려면 아래 카테고리를 선택하세요.',
    'diseases.info.soon': '정보가 곧 추가될 예정입니다',
    'diseases.label.symptoms': '증상',
    'diseases.label.treatment': '치료 / 집에서의 케어',
    'diseases.data.fever.1.name': '일반 감기',
    'diseases.data.fever.1.symptoms': '콧물, 미열, 기침',
    'diseases.data.fever.1.treatment': '충분한 수분 공급과 휴식을 취하세요. 코막힘에 식염수를 사용하십시오. 4세 이하 어린이의 경우 소아과 의사와 상담하지 않고 시판 기침약을 사용하는 것을 피하십시오.',
    'diseases.data.fever.2.name': '독감 (인플루엔자)',
    'diseases.data.fever.2.symptoms': '고열, 근육통, 피로',
    'diseases.data.fever.2.treatment': '소아과 의사가 승인한 아세트아미노펜과 같은 해열제를 투여합니다. 호흡 곤란이나 평소와 다르게 심한 무기력증이 있는 경우 즉시 치료를 받으십시오.',
    'diseases.data.digestive.1.name': '위장염',
    'diseases.data.digestive.1.symptoms': '구토, 설사, 복통',
    'diseases.data.digestive.1.treatment': '자주 적은 양의 경구 수액제(ORS)를 투여하는 데 우선순위를 두십시오. 자극적이지 않은 음식(BRAT 식단)을 점차적으로 도입하십시오. 유제품과 단 음료는 피하십시오.',
    'diseases.data.respiratory.1.name': '천식',
    'diseases.data.respiratory.1.symptoms': '천명음, 숨가쁨, 흉부 압박감',
    'diseases.data.respiratory.1.treatment': '처방된 천식 행동 계획을 엄격하게 따르십시오. 악화될 시 속효성 흡입기를 사용하십시오. 먼지 및 애완동물 비듬과 같은 환경 유발 요인을 최소화하십시오.',
    'diseases.data.respiratory.2.name': '기관지염',
    'diseases.data.respiratory.2.symptoms': '가래 있는 기침, 피로감, 미열',
    'diseases.data.respiratory.2.treatment': '가습기를 사용하고 점액을 묽게 하기 위해 충분히 수분을 섭취합니다. 기침이 2-3주 이상 지속되거나 악화되면 의사와 상담하십시오.',
    'diseases.data.skin.1.name': '습진',
    'diseases.data.skin.1.symptoms': '건조하고 가렵고 붉은 반점',
    'diseases.data.skin.1.treatment': '목욕 후 즉시 두꺼운 무향 보습제를 바르십시오. 조절되지 않을 때는 처방받은 국소 코르티코스테로이드를 사용하십시오.',
    'diseases.data.skin.2.name': '수두',
    'diseases.data.skin.2.symptoms': '가려운 수포, 발열, 피로',
    'diseases.data.skin.2.treatment': '가려움증 완화를 위해 칼라민 로션이나 오트밀 목욕을 하세요. 이차 세균 감염을 방지하기 위해 손톱을 짧게 자르세요. 아세트아미노펜을 투여하십시오 (아스피린은 절대 피하십시오).',
    'diseases.data.allergies.1.name': '계절성 알레르기',
    'diseases.data.allergies.1.symptoms': '재채기, 콧물, 눈 가려움',
    'diseases.data.allergies.1.treatment': '비진정성 2세대 항히스타민제를 투여합니다. HEPA 공기청정기를 사용하고 꽃가루가 많은 계절에는 창문을 닫아 두십시오.',
    'qa.title': 'AI 의료 어시스턴트',
    'qa.subtitle': '아이의 건강, 질병 또는 관리 방법에 대해 질문하세요.',
    'qa.placeholder': '여기에 질문을 입력하세요...',
    'qa.send': '전송',
    'qa.error.empty': '죄송합니다. 정보를 찾을 수 없습니다.',
    'qa.error.connect': 'AI 지원팀에 연결하는 중 오류가 발생했습니다. 나중에 다시 시도해 주세요.',
    'qa.disclaimer': '(저는 투르크멘어, 러시아어, 영어, 독일어 및 한국어를 구사할 수 있습니다)',
    'qa.thinking': '생각 중...', 'qa.assistant': '어시스턴트',
    'tuina.header.subtitle': '추나는 균형을 회복하고 치료에 초점을 맞춘 고대 중국의 치료용 마사지 기법입니다.',
    'tuina.benefits.1': '혈액 순환을 개선하고 휴식을 촉진합니다.',
    'tuina.benefits.2': '근육 긴장과 관절통을 완화합니다.',
    'tuina.benefits.3': '스트레스와 불안을 유발하는 요소를 감소시킵니다.',
    'tuina.benefits.4': '아이들의 소화 및 호흡기 문제를 도와줍니다.',
    'tuina.benefits.5': '유연성과 움직임의 범위를 개선합니다.',
    'tuina.techniques.title': '일반적인 추나 기법',
    'tuina.tech.1.title': '반죽하기 (Kneading)',
    'tuina.tech.1.desc': '손가락을 이용해 원을 그리며 근육을 이완시키고 혈류를 개선합니다.',
    'tuina.tech.2.title': '구르기 (Rolling)',
    'tuina.tech.2.desc': '사지 또는 척추를 따라 부드럽게 구르는 동작을 통해 뻣뻣함과 긴장을 완화합니다.',
    'tuina.tech.3.title': '누르기 (Pressing)',
    'tuina.tech.3.desc': '주요 혈자리에 직접적인 압력을 가해 기의 흐름을 자극하고 통증을 완화합니다.',
    'tuina.steps.title2': '추나 마사지 수행 방법: 단계별 안내',
    'tuina.step2.1': '1단계: 어린이 또는 환자를 편안하게 등을 대고 눕힙니다.',
    'tuina.step2.2': '2단계: 어깨를 둥글게 반죽하듯 부드럽게 주무르면서 근육을 풀어줍니다.',
    'tuina.step2.3': '3단계: 등과 척추에 굴리는 동작을 사용하여 피로를 풀어줍니다.',
    'tuina.step2.4': '4단계: 경락을 따라 혈자리에 가벼운 압박을 가하여 균형을 회복시킵니다.',
    'tuina.step2.5': '5단계: 부드럽고 매끄러운 동작으로 마무리하여 몸과 마음을 진정시킵니다.',
    'tuina.whentouse.title': '추나 마사지는 언제 받아야 할까요',
    'tuina.whentouse.intro': '추나는 아이와 어른 모두의 다음 질환을 치료하는 데 효과적입니다:',
    'tuina.whentouse.1': '변비나 복부 팽만감과 같은 소화기 문제.',
    'tuina.whentouse.2': '천식 및 기침과 같은 호흡기 질환.',
    'tuina.whentouse.3': '근육통, 뻣뻣함 및 관절 문제.',
    'tuina.whentouse.4': '스트레스 완화, 이완 및 수면 질 개선.',
    'tuina.children.title': '어린이를 위한 추나',
    'tuina.children.desc': '어린이용 추나는 아이의 필요에 맞춘 부드러운 압력과 달래는 기법으로 변형하여 사용할 수 있습니다. 약물을 사용하지 않고 아이들의 불편함을 완화시키는 데에 특히 도움이 됩니다.',
    'tuina.video.title': '비디오 튜토리얼 보기',
    'tuina.faq.title': '자주 묻는 질문',
    'tuina.faq.1.q': '이것은 안전한가요?',
    'tuina.faq.1.a': '네, 훈련받은 전문가에 의해 안전하게 수행되며, 어린이들도 받을 수 있도록 매우 부드럽게 조정됩니다.',
    'tuina.faq.2.q': '마사지 시간은 얼마나 지속되나요?',
    'tuina.faq.2.a': '어린이의 일반적인 세션은 아이의 연령과 상태에 따라 15-30분 정도 걸립니다.',
    'tuina.faq.3.q': '부모가 기대할 수 있는 효과는 무엇인가요?',
    'tuina.faq.3.a': '자녀가 훨씬 편안하고 푹 쉰 것을 느낄 수 있습니다. 이것은 전통적인 소아의학과 병행하는 보완 치료법으로 작용합니다.',
    'tuina.body.title': '신체 부위 및 기법',
    'tuina.body.1.title': '1. 머리와 얼굴',
    'tuina.body.1.how': '수행 방법: 이마: 손가락으로 이마에 작고 둥근 원을 그리며 가볍게 문지릅니다. 관자놀이: 양쪽 관자놀이를 가볍게 원을 그리며 마사지합니다. 눈 주위: 긴장을 완화하기 위해 눈과 눈썹 주위를 가볍게 누릅니다.',
    'tuina.body.1.benefits': '효과: 두통을 완화하고 눈의 피로를 감소시키며 아이가 차분해질 수 있도록 돕습니다.',
    'tuina.body.1.when': '언제 수행하나요: 아이가 잠들기 전 긴장을 풀어줄 때, 화면을 본 후나 스트레스 받는 활동 후에 눈의 피로를 줄이고 싶을 때.',
    'tuina.body.2.title': '2. 목과 어깨',
    'tuina.body.2.how': '수행 방법: 목: 엄지손가락으로 목을 따라 위치한 근육을 부드럽게 누르고 마사지합니다. 어깨: 손바닥으로 어깨 근육 위를 부드럽게 원형으로 마사지합니다.',
    'tuina.body.2.benefits': '효과: 목과 어깨의 긴장을 풀어주고, 올바른 자세에 도움을 주며 스트레스를 해소시킵니다.',
    'tuina.body.2.when': '언제 수행하나요: 긴 시간 앉아 있거나 놀이를 한 후에. 아이가 긴장하거나 스트레스를 받을 때.',
    'tuina.body.3.title': '3. 팔과 손',
    'tuina.body.3.how': '수행 방법: 팔: 가벼운 손길로 팔뚝을 위아래로 문지릅니다. 손: 엄지손가락으로 원을 그리며 손바닥과 손가락을 부드럽게 마사지합니다.',
    'tuina.body.3.benefits': '효과: 혈액 순환을 개선하고, 유연성을 증진시키며 손의 긴장을 완화시킵니다.',
    'tuina.body.3.when': '언제 수행하나요: 글씨를 쓰거나 기기를 사용한 후. 운동 전후 유연성을 높이기 위해.',
    'tuina.body.4.title': '4. 등과 척추',
    'tuina.body.4.how': '수행 방법: 척추: 손가락이나 엄지로 목에서 위부터 아래로 척추를 따라 부드럽게 마사지합니다. 허리 아래쪽: 아래 등 쪽에 가벼운 압력을 주고 손바닥으로 원 모양을 그리면서 부드럽게 마사지해줍니다.',
    'tuina.body.4.benefits': '효과: 등 통증을 완화하고 자세를 교정해 주며 휴식을 촉진합니다.',
    'tuina.body.4.when': '언제 수행하나요: 달리기나 스포츠와 같은 활동을 한 후에. 등에 피로를 덜어주기 위해 체류 후 장시간 자리에 앉아 있은 후.',
    'tuina.body.5.title': '5. 다리와 발',
    'tuina.body.5.how': '수행 방법: 발: 엄지손가락을 사용하여 발바닥과 발가락을 부드럽게 원을 그리며 마사지합니다. 다리: 다리부터 허벅지까지 긴 스트로크로 마사지합니다. 종아리와 허벅지를 가볍게 눌러줍니다.',
    'tuina.body.5.benefits': '효과: 다리에 나는 쥐를 완화시키고 혈류를 개선하며 아이가 건강하게 자랄 수 있도록 돕습니다.',
    'tuina.body.5.when': '언제 수행하나요: 뛰거나 운동을 하는 피지컬 활동 전과 후. 잠을 설치지 않고 편안하게 자도록 자기 전.',
    'tuina.timing.title': '추나 마사지는 언제 수행되어야 합니까?',
    'tuina.timing.daily': '매일 시행할 수 있습니다: 긴장을 풀고 건강한 신체를 위해 매일 실시할 수 있습니다.',
    'tuina.timing.special': '특별할 때: 운동과 엑티비티 활동 이후. 아이가 긴장하고 스트레스 받아 근육통을 가질 때. 그리고 두통이나 배탈 및 소화 불량시 수면의 질을 개선하기 위해.',
    'tuina.keybenefits.title': '어린이를 위한 추나 마사지의 핵심적인 장점들',
    'tuina.keybenefits.health': '건강상의 이점: 혈액 순환을 개선시키고 면역 체계를 강화하여 전반적인 건강 증진을 도모합니다.',
    'tuina.keybenefits.relieves': '일반적인 문제를 완화: 근육통, 두통, 소화 불량 증상을 가라앉혀줍니다.',
    'tuina.keybenefits.sleep': '수면 개선: 마음의 안정을 주고 우리 아이가 질 좋은 수면을 할 수 있도록 유도해 줍니다.',
    'footer.text': '© 2026 건강한 아이들(Sagdyn Çagalar). 판권 소유. 면책 조항: 이 웹사이트는 정보 제공의 목적으로만 사용되며 전문가의 의학적 조언을 대체하지 않습니다.'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tk');
  const [isLanguageSelected, setIsLanguageSelected] = useState<boolean>(false);

  // When language changes, update the document title and HTML lang attribute
  React.useEffect(() => {
    document.documentElement.lang = language;
    document.title = translations[language]['app.title'] || 'Sagdyn Çagalar';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLanguageSelected, setIsLanguageSelected }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;

};